<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Alessandro de Castro Corrêa">

<title>Estatística básica para experimentos</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-efbb37e9afcc02144ebbc7afd12a776f.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#termos-básicos" id="toc-termos-básicos" class="nav-link active" data-scroll-target="#termos-básicos"><span class="header-section-number">1</span> Termos Básicos</a>
  <ul class="collapse">
  <li><a href="#classificação-das-variáveis" id="toc-classificação-das-variáveis" class="nav-link" data-scroll-target="#classificação-das-variáveis"><span class="header-section-number">1.1</span> Classificação das variáveis</a></li>
  <li><a href="#tipos-de-comparações-das-amostras" id="toc-tipos-de-comparações-das-amostras" class="nav-link" data-scroll-target="#tipos-de-comparações-das-amostras"><span class="header-section-number">1.2</span> Tipos de comparações das amostras</a></li>
  </ul></li>
  <li><a href="#estatísticas-descritivas" id="toc-estatísticas-descritivas" class="nav-link" data-scroll-target="#estatísticas-descritivas"><span class="header-section-number">2</span> Estatísticas descritivas</a>
  <ul class="collapse">
  <li><a href="#medidas-de-posição-central" id="toc-medidas-de-posição-central" class="nav-link" data-scroll-target="#medidas-de-posição-central"><span class="header-section-number">2.1</span> Medidas de posição central</a></li>
  <li><a href="#medidas-de-dispersão" id="toc-medidas-de-dispersão" class="nav-link" data-scroll-target="#medidas-de-dispersão"><span class="header-section-number">2.2</span> Medidas de dispersão</a></li>
  <li><a href="#medidas-de-posição-não-central" id="toc-medidas-de-posição-não-central" class="nav-link" data-scroll-target="#medidas-de-posição-não-central"><span class="header-section-number">2.3</span> Medidas de posição não central</a></li>
  <li><a href="#gráficos" id="toc-gráficos" class="nav-link" data-scroll-target="#gráficos"><span class="header-section-number">2.4</span> Gráficos</a>
  <ul class="collapse">
  <li><a href="#boxplot" id="toc-boxplot" class="nav-link" data-scroll-target="#boxplot"><span class="header-section-number">2.4.1</span> Boxplot</a></li>
  <li><a href="#histograma" id="toc-histograma" class="nav-link" data-scroll-target="#histograma"><span class="header-section-number">2.4.2</span> Histograma</a></li>
  <li><a href="#exercício" id="toc-exercício" class="nav-link" data-scroll-target="#exercício"><span class="header-section-number">2.4.3</span> Exercício</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#probabilidades" id="toc-probabilidades" class="nav-link" data-scroll-target="#probabilidades"><span class="header-section-number">3</span> Probabilidades</a>
  <ul class="collapse">
  <li><a href="#distribuições-de-probabilidades" id="toc-distribuições-de-probabilidades" class="nav-link" data-scroll-target="#distribuições-de-probabilidades"><span class="header-section-number">3.1</span> Distribuições de probabilidades</a></li>
  <li><a href="#diferença-ente-distribuição-de-probabilidades-e-distribuição-de-frequências" id="toc-diferença-ente-distribuição-de-probabilidades-e-distribuição-de-frequências" class="nav-link" data-scroll-target="#diferença-ente-distribuição-de-probabilidades-e-distribuição-de-frequências"><span class="header-section-number">3.2</span> Diferença ente distribuição de probabilidades e distribuição de frequências</a></li>
  <li><a href="#distribuição-de-frequências-de-dados-experimentais" id="toc-distribuição-de-frequências-de-dados-experimentais" class="nav-link" data-scroll-target="#distribuição-de-frequências-de-dados-experimentais"><span class="header-section-number">3.3</span> Distribuição de frequências de dados experimentais</a>
  <ul class="collapse">
  <li><a href="#criando-uma-tabela-de-distribuição-de-frequências" id="toc-criando-uma-tabela-de-distribuição-de-frequências" class="nav-link" data-scroll-target="#criando-uma-tabela-de-distribuição-de-frequências"><span class="header-section-number">3.3.1</span> Criando uma tabela de distribuição de frequências</a></li>
  <li><a href="#criando-um-histograma" id="toc-criando-um-histograma" class="nav-link" data-scroll-target="#criando-um-histograma"><span class="header-section-number">3.3.2</span> Criando um histograma</a></li>
  <li><a href="#criando-histogramas-personalizados" id="toc-criando-histogramas-personalizados" class="nav-link" data-scroll-target="#criando-histogramas-personalizados"><span class="header-section-number">3.3.3</span> Criando histogramas personalizados</a></li>
  <li><a href="#exercício-1" id="toc-exercício-1" class="nav-link" data-scroll-target="#exercício-1"><span class="header-section-number">3.3.4</span> Exercício</a></li>
  </ul></li>
  <li><a href="#densidade" id="toc-densidade" class="nav-link" data-scroll-target="#densidade"><span class="header-section-number">3.4</span> Densidade</a></li>
  </ul></li>
  <li><a href="#a-distribuição-normal" id="toc-a-distribuição-normal" class="nav-link" data-scroll-target="#a-distribuição-normal"><span class="header-section-number">4</span> A distribuição Normal</a>
  <ul class="collapse">
  <li><a href="#a-características-da-curva-normal" id="toc-a-características-da-curva-normal" class="nav-link" data-scroll-target="#a-características-da-curva-normal"><span class="header-section-number">4.1</span> A características da curva normal</a></li>
  <li><a href="#a-curva-normal-padronizada" id="toc-a-curva-normal-padronizada" class="nav-link" data-scroll-target="#a-curva-normal-padronizada"><span class="header-section-number">4.2</span> A Curva Normal Padronizada</a></li>
  <li><a href="#escores-padronizados" id="toc-escores-padronizados" class="nav-link" data-scroll-target="#escores-padronizados"><span class="header-section-number">4.3</span> Escores padronizados</a></li>
  <li><a href="#distribuição-t" id="toc-distribuição-t" class="nav-link" data-scroll-target="#distribuição-t"><span class="header-section-number">4.4</span> Distribuição <em>t</em></a></li>
  <li><a href="#a-estimativa" id="toc-a-estimativa" class="nav-link" data-scroll-target="#a-estimativa"><span class="header-section-number">4.5</span> A Estimativa</a>
  <ul class="collapse">
  <li><a href="#o-conceito-de-intervalo-de-estimação" id="toc-o-conceito-de-intervalo-de-estimação" class="nav-link" data-scroll-target="#o-conceito-de-intervalo-de-estimação"><span class="header-section-number">4.5.1</span> O conceito de intervalo de estimação</a></li>
  <li><a href="#intervalo-de-confiança" id="toc-intervalo-de-confiança" class="nav-link" data-scroll-target="#intervalo-de-confiança"><span class="header-section-number">4.5.2</span> Intervalo de confiança</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#teste-de-hipóteses" id="toc-teste-de-hipóteses" class="nav-link" data-scroll-target="#teste-de-hipóteses"><span class="header-section-number">5</span> Teste de hipóteses</a>
  <ul class="collapse">
  <li><a href="#tipos-de-erros-em-um-teste-de-hipóteses" id="toc-tipos-de-erros-em-um-teste-de-hipóteses" class="nav-link" data-scroll-target="#tipos-de-erros-em-um-teste-de-hipóteses"><span class="header-section-number">5.1</span> Tipos de erros em um teste de hipóteses</a></li>
  <li><a href="#valor-p-e-alfa" id="toc-valor-p-e-alfa" class="nav-link" data-scroll-target="#valor-p-e-alfa"><span class="header-section-number">5.2</span> Valor P e alfa</a></li>
  <li><a href="#teste-de-hipótese-para-uma-amostra-variância-desconhecida" id="toc-teste-de-hipótese-para-uma-amostra-variância-desconhecida" class="nav-link" data-scroll-target="#teste-de-hipótese-para-uma-amostra-variância-desconhecida"><span class="header-section-number">5.3</span> Teste de hipótese para uma amostra (variância desconhecida)</a>
  <ul class="collapse">
  <li><a href="#exemplo" id="toc-exemplo" class="nav-link" data-scroll-target="#exemplo"><span class="header-section-number">5.3.1</span> Exemplo</a></li>
  <li><a href="#procedimentos" id="toc-procedimentos" class="nav-link" data-scroll-target="#procedimentos"><span class="header-section-number">5.3.2</span> Procedimentos</a></li>
  </ul></li>
  <li><a href="#análise-de-normalidade" id="toc-análise-de-normalidade" class="nav-link" data-scroll-target="#análise-de-normalidade"><span class="header-section-number">5.4</span> Análise de normalidade</a>
  <ul class="collapse">
  <li><a href="#análise-gráfica-da-normalidade" id="toc-análise-gráfica-da-normalidade" class="nav-link" data-scroll-target="#análise-gráfica-da-normalidade"><span class="header-section-number">5.4.1</span> Análise gráfica da normalidade</a></li>
  <li><a href="#testes-de-normalidade" id="toc-testes-de-normalidade" class="nav-link" data-scroll-target="#testes-de-normalidade"><span class="header-section-number">5.4.2</span> Testes de normalidade</a></li>
  <li><a href="#exercício-2" id="toc-exercício-2" class="nav-link" data-scroll-target="#exercício-2"><span class="header-section-number">5.4.3</span> Exercício</a></li>
  </ul></li>
  <li><a href="#teste-de-hipótese-para-um-fator-com-dois-níveis-duas-amostras-independentes." id="toc-teste-de-hipótese-para-um-fator-com-dois-níveis-duas-amostras-independentes." class="nav-link" data-scroll-target="#teste-de-hipótese-para-um-fator-com-dois-níveis-duas-amostras-independentes."><span class="header-section-number">5.5</span> Teste de hipótese para um fator com dois níveis (duas amostras independentes).</a>
  <ul class="collapse">
  <li><a href="#teste-de-normalidade-dos-dados" id="toc-teste-de-normalidade-dos-dados" class="nav-link" data-scroll-target="#teste-de-normalidade-dos-dados"><span class="header-section-number">5.5.1</span> Teste de normalidade dos dados</a></li>
  <li><a href="#teste-de-homogeneidade-das-variâncias-homocedasticidade" id="toc-teste-de-homogeneidade-das-variâncias-homocedasticidade" class="nav-link" data-scroll-target="#teste-de-homogeneidade-das-variâncias-homocedasticidade"><span class="header-section-number">5.5.2</span> Teste de homogeneidade das variâncias (Homocedasticidade)</a></li>
  <li><a href="#o-teste-t-para-dois-tratamentos-independentes" id="toc-o-teste-t-para-dois-tratamentos-independentes" class="nav-link" data-scroll-target="#o-teste-t-para-dois-tratamentos-independentes"><span class="header-section-number">5.5.3</span> O teste t para dois tratamentos independentes</a></li>
  </ul></li>
  </ul></li>
  </ul>
</nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content" id="quarto-document-content">
<div style="text-align: center; margin-top: 20px;">

  <img src="Figuras/logo_ppgemat.jpg" style="width: 150px;">

</div>

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Estatística básica para experimentos</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Autor</div>
  <div class="quarto-title-meta-heading">Afiliação</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Alessandro de Castro Corrêa <a href="mailto:alessandro.correa@ifpa.edu.br" class="quarto-title-author-email"><i class="bi bi-envelope"></i></a> </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Instituto Federal do Pará - IFPA
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="termos-básicos" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Termos Básicos</h1>
<ul>
<li><strong>População</strong>: é o conjunto de objetos, indivíduos ou resultados experimentais acerca do qual se pretende estudar alguma característica.</li>
<li><strong>Amostra</strong>: parte representativa dos elementos de uma população.</li>
<li><strong>Amostragem</strong>: processo de seleção de amostra.</li>
<li><strong>Variável</strong>: qualidade ou quantidade, medida ou registrada para cada sujeito da amostra.
<ul>
<li>Ex.: sexo, idade, resistência.</li>
</ul></li>
<li><strong>Variável aleatória</strong>: é uma variável cujo valor não é conhecido até seja observada, logo não pode ser previsto com certeza.</li>
<li><strong>Observação</strong>: unidade de estudo, sujeito ou indivíduos.</li>
<li><strong>Parâmetro</strong>: característica da população
<ul>
<li>Ex.: Quantidade de indivíduos, valor médio (<span class="math inline">\(\mu\)</span>), a nota média de uma escola, desvio padrão (<span class="math inline">\(\sigma\)</span>).</li>
</ul></li>
<li><strong>Estimação</strong>: processo de utilizar dados amostrais para estimar os valores dos parâmetros populacionais desconhecidos.
<ul>
<li>Ex.: nota média amostral (<span class="math inline">\(\bar{x}\)</span>), desvio-padrão amostral (<span class="math inline">\(s\)</span>).</li>
</ul></li>
<li><strong>Estimador</strong>: função (fórmula) que estima um parâmetro a partir de dados amostrais. <span class="math display">\[\bar{x}=\dfrac{\sum\limits_ {i=1}^n x}{n}\]</span></li>
<li><strong>Estimativa (estatística)</strong>: o valor da estimativa. <span class="math display">\[\bar{x}=\dfrac{4+5+6}{3}=5\]</span></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-pop_amostra" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-pop_amostra-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: População e amostra
</figcaption>
<div aria-describedby="fig-pop_amostra-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/img_pop_amostra.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
</figure>
</div>
</div>
</div>
<section id="classificação-das-variáveis" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="classificação-das-variáveis"><span class="header-section-number">1.1</span> Classificação das variáveis</h2>
<ul>
<li>Qualitativas
<ul>
<li>Categóricas (nominais)</li>
<li>Ordinais</li>
</ul></li>
<li>Quantitativas
<ul>
<li>Discretas</li>
<li>Contínuas</li>
</ul></li>
</ul>
</section>
<section id="tipos-de-comparações-das-amostras" class="level2" data-number="1.2">
<h2 data-number="1.2" class="anchored" data-anchor-id="tipos-de-comparações-das-amostras"><span class="header-section-number">1.2</span> Tipos de comparações das amostras</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-independentes" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-independentes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Independentes (Não Pareadas ou Não relacionadas)
</figcaption>
<div aria-describedby="fig-independentes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/img_independentes.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-dependentes" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-dependentes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Dependentes (Pareadas ou Relacionadas)
</figcaption>
<div aria-describedby="fig-dependentes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/img_dependentes.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="estatísticas-descritivas" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Estatísticas descritivas</h1>
<p>A análise de dados deve iniciar com análise exploratória através da inspeção das estatísticas descritivas, tabelas e de seus aspectos visuais com propósito de compreender melhor seu comportamento, tendências, variabilidade e identificar eventuais de valores atípicos (<em>outliers</em>).</p>
<p>As medidas estatística descritas na tabela a seguir são aplicáveis somente a <strong>dados quantitivos</strong> (variáveis discretas e contínuas).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 27%">
<col style="width: 42%">
<col style="width: 18%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th>Medida</th>
<th>Equação</th>
<th>Comandos no R</th>
<th>Pacote</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>média</td>
<td><span class="math inline">\(\bar{x}=\dfrac{\sum\limits_ {i=1}^n x}{n}\)</span></td>
<td><code>mean(x)</code></td>
<td>Base</td>
</tr>
<tr class="even">
<td>Mediana</td>
<td></td>
<td><code>median(x)</code></td>
<td>Base</td>
</tr>
<tr class="odd">
<td>Amplitude</td>
<td><span class="math inline">\(A=x_{max}-x_{min}\)</span></td>
<td><code>range(x)</code></td>
<td>Base</td>
</tr>
<tr class="even">
<td>variância</td>
<td><span class="math inline">\(s^2=\dfrac{\sum\limits_{i=1}^n (x_i-\bar{x})^2}{n-1}\)</span></td>
<td><code>var(x)</code></td>
<td>Base</td>
</tr>
<tr class="odd">
<td>Desvio-padrão</td>
<td><span class="math inline">\(s=\sqrt{s^2}\)</span></td>
<td><code>sd(x)</code></td>
<td>Base</td>
</tr>
<tr class="even">
<td>Coeficiente de variação</td>
<td><span class="math inline">\(cv=\dfrac{s}{\bar{x}}\)</span></td>
<td><code>sd(x)/mean(x)</code></td>
<td>Base</td>
</tr>
<tr class="odd">
<td>Erro-padrão</td>
<td><span class="math inline">\(ep=\sqrt{\dfrac{s^2}{n}}\)</span> ou <span class="math inline">\(ep=\dfrac{s}{\sqrt{n}}\)</span></td>
<td><code>s/sqrt(length(x))</code></td>
<td>Base</td>
</tr>
<tr class="even">
<td>Quartis</td>
<td></td>
<td><code>quantile(x)</code></td>
<td>Base</td>
</tr>
<tr class="odd">
<td>Intervalo Inter-quartil</td>
<td><span class="math inline">\(IQR=q_3-q_1\)</span></td>
<td><code>IQR(x)</code></td>
<td>Base</td>
</tr>
<tr class="even">
<td>Decis</td>
<td></td>
<td><code>quantile(x, seq(from=0.1, to=0.9, 0.1))</code></td>
<td>Base</td>
</tr>
<tr class="odd">
<td>Centis</td>
<td></td>
<td><code>quantile(x, .01)# 1o centil</code></td>
<td>Base</td>
</tr>
<tr class="even">
<td>Mínimo e Máximo</td>
<td></td>
<td><code>min(x)</code> e <code>max</code></td>
<td>Base</td>
</tr>
<tr class="odd">
<td>Assimetria</td>
<td></td>
<td><code>skewness(x)</code></td>
<td>e1071</td>
</tr>
<tr class="even">
<td>Curtose</td>
<td></td>
<td><code>kurtosis(x)</code></td>
<td>e1071</td>
</tr>
</tbody>
</table>
<section id="medidas-de-posição-central" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="medidas-de-posição-central"><span class="header-section-number">2.1</span> Medidas de posição central</h2>
<p>A <strong>média aritmética</strong> de uma amostra, é um número que, levando em conta o total de elementos da amostra, pode substituir a todos, sem alterar determinada característica desse conjunto.</p>
<p>A <strong>mediana</strong> é valor que ocupa a posição central da listagem, estando a amostra com seus valores em ordem crescente ou decrescente e com todos os valores repetidos também incluídos, individualmente, na lista ordenada. Quando a quantidade de valores é ímpar, a mediana da amostra é o valor que ocupa a posição, central, posição única. Quando a quantidade de valores é par, há duas posições centrais na lista ordenada; então a mediana da amostra é a média aritmética dos valores que ocupam as posições centrais.</p>
</section>
<section id="medidas-de-dispersão" class="level2" data-number="2.2">
<h2 data-number="2.2" class="anchored" data-anchor-id="medidas-de-dispersão"><span class="header-section-number">2.2</span> Medidas de dispersão</h2>
<p>A <strong>amplitude</strong> é a diferença entre o maior e o menor valor</p>
<p>A <strong>Variância</strong> é uma medida de dispersão dos dados em relação é média, medida em unidades ao quadro dos dados.</p>
<p>O <strong>desvio padrão</strong> é uma medida de dispersão e o seu valor reflete a variabilidade das observações em relação é média. O erro padrão da estimativa diminui com o aumento do tamanho da amostra, refletindo o aumento de precisão da estimativa com o tamanho da amostra. Se o objetivo é descrever a variabilidade observada numa amostra deve-se utilizar o desvio padrão.</p>
<p>O <strong>erro padrão</strong> é uma medida do erro envolvido na estimação de um parâmetro a partir de uma amostra. É usual apresentar a média e o erro padrão da média com a indicação <span class="math inline">\((\bar{x}\pm e)\)</span>. Indica a imprecisão associada à estimativa de um determinado parâmetro (e.g.&nbsp;média).</p>
<p>O <strong>coeficiente de variação</strong> fornece uma medida de variabilidade dos dados em relação à média. Quando menor for o CV, mais homogênea é a amostra ou experimento. A classificação do CV depende do processo que se estuda.</p>
<p>classificação do CV segundo Pimentel e Gomes (1985), baseada em ensaios agrícolas.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">valor de CV</th>
<th>classificação</th>
<th>Interpretação</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;"><span class="math inline">\(CV\leq 10\%\)</span></td>
<td>Baixo</td>
<td>Baixa dispersão dos dados</td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="math inline">\(10\% &lt; CV \leq 20\%\)</span></td>
<td>Médio</td>
<td>Média dispersão dos dados</td>
</tr>
<tr class="odd">
<td style="text-align: right;"><span class="math inline">\(20\% &lt; CV \leq  30\%\)</span></td>
<td>Alto</td>
<td>Alta dispersão dos dados</td>
</tr>
<tr class="even">
<td style="text-align: right;"><span class="math inline">\(CV &gt;30\%\)</span></td>
<td>Muito Alto</td>
<td>Dispersão muito alta dos dados</td>
</tr>
</tbody>
</table>
</section>
<section id="medidas-de-posição-não-central" class="level2" data-number="2.3">
<h2 data-number="2.3" class="anchored" data-anchor-id="medidas-de-posição-não-central"><span class="header-section-number">2.3</span> Medidas de posição não central</h2>
<p>Os <strong>quartis (Q1, Q2 e Q3)</strong>: são valores que dividem a distribuição da amostra ordenada em ordem crescente em quatro partes iguais. O primeiro quartil, Q1, é o número que deixa 25% das observações abaixo, o terceiro quartil, Q3, deixa 75% das observações abaixo.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-quartis" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-quartis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Quartis da distribuição
</figcaption>
<div aria-describedby="fig-quartis-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/img_quartis.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
</figure>
</div>
</div>
</div>
<p>Os <strong>decis (D1, D2, …, D9)</strong> dividem os dados em dez partes (cada parte tem 10% dos dados).</p>
<p>Os <strong>percentis (P1, P2, …, P99)</strong> dividem os dados em centésimas partes (cada parte tem 1% dos dados).</p>
<p><strong>Assimetria</strong> é uma medidade de assimetria da distribuição.</p>
<div class="cell" data-fig.hight="3">
<div class="cell-output-display">
<div id="fig-assimetria" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-assimetria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Assimetria
</figcaption>
<div aria-describedby="fig-assimetria-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-assimetria-1.png" class="img-fluid figure-img" width="864">
</div>
</figure>
</div>
</div>
</div>
<p><br> <strong>Curtose</strong> é uma medida que caracteriza o achatamento da distribuição de frequência em relação à curva normal padrão (Gauss).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-curtose" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-curtose-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6: Curtose
</figcaption>
<div aria-describedby="fig-curtose-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-curtose-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Vamos analisar os dados de experimentos de tempo de vida útil de baterias em anos que estão no documento <a href="bateria.RData"><strong>bateria.RData</strong></a>. Iniciamos importando os dados e examinado o objeto baterias que é um data frame que possui uma variável denominada vida_util, com 40 observações.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Importação, preparação e inspeção</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"bateria.RData"</span>) <span class="co"># carregar dados em .RData</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(bateria)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "vida_util"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(bateria)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 40  1</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bateria)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  vida_util
1       2.2
2       4.1
3       3.5
4       4.5
5       3.2
6       3.7</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(bateria) <span class="co"># Estrutura resumida</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   40 obs. of  1 variable:
 $ vida_util: num  2.2 4.1 3.5 4.5 3.2 3.7 3 2.6 3.4 1.6 ...</code></pre>
</div>
</div>
<p>Pode-se iniciar a análise examinando as estatísticas mais básicas como o comando <code>summary()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estatisticas descritivas</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bateria)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   vida_util    
 Min.   :1.600  
 1st Qu.:3.100  
 Median :3.400  
 Mean   :3.413  
 3rd Qu.:3.825  
 Max.   :4.700  </code></pre>
</div>
</div>
<p>Contudo, talvez possamos preferir uma tabela personalizada de estatísticas, podendo inclusive gerar um data.frame que conterá nossas estatísticas. Para tanto, utilizaremos o comando <code>rbind()</code> que organiza nossos objetos em linhas (o <code>cbind()</code> organiza em colunas).</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(bateria<span class="sc">$</span>vida_util) <span class="co"># No de obs.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(bateria<span class="sc">$</span>vida_util) <span class="co"># média</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>md <span class="ot">&lt;-</span> <span class="fu">median</span>(bateria<span class="sc">$</span>vida_util) <span class="co"># Mediana</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>var <span class="ot">&lt;-</span> <span class="fu">var</span>(bateria<span class="sc">$</span>vida_util) <span class="co">#variância</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sd</span>(bateria<span class="sc">$</span>vida_util)  <span class="co"># desvio-padrão</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a>cv <span class="ot">&lt;-</span> s<span class="sc">/</span>xbar<span class="sc">*</span><span class="dv">100</span> <span class="co"># Coeficiente de variação</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>ep <span class="ot">&lt;-</span> s<span class="sc">/</span><span class="fu">sqrt</span>(n) <span class="co"># erro-padrão</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>min.X <span class="ot">&lt;-</span> <span class="fu">min</span>(bateria<span class="sc">$</span>vida_util)</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>max.X <span class="ot">&lt;-</span> <span class="fu">max</span>(bateria<span class="sc">$</span>vida_util)</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(e1071)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>skew.X <span class="ot">&lt;-</span> <span class="fu">skewness</span>(bateria<span class="sc">$</span>vida_util)</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a>kur.X <span class="ot">&lt;-</span> <span class="fu">kurtosis</span>(bateria<span class="sc">$</span>vida_util)</span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Tabela com estatísticas descritivas</span></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a>vida.desc <span class="ot">&lt;-</span> <span class="fu">rbind</span>(n,xbar, md,s,var,s, cv, ep, min.X,max.X, skew.X,kur.X) <span class="co"># em linhas</span></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(vida.desc) <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"estatísticas"</span>)</span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a>vida.desc</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>       estatísticas
n       40.00000000
xbar     3.41250000
md       3.40000000
s        0.70281029
var      0.49394231
s        0.70281029
cv      20.59517342
ep       0.11112406
min.X    1.60000000
max.X    4.70000000
skew.X  -0.33685001
kur.X    0.01260685</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">quantile</span>(bateria<span class="sc">$</span>vida_util)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   0%   25%   50%   75%  100% 
1.600 3.100 3.400 3.825 4.700 </code></pre>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-strip" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-strip-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;7: Observações dos tempos de vida útil de baterias em anos
</figcaption>
<div aria-describedby="fig-strip-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-strip-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="gráficos" class="level2" data-number="2.4">
<h2 data-number="2.4" class="anchored" data-anchor-id="gráficos"><span class="header-section-number">2.4</span> Gráficos</h2>
<section id="boxplot" class="level3" data-number="2.4.1">
<h3 data-number="2.4.1" class="anchored" data-anchor-id="boxplot"><span class="header-section-number">2.4.1</span> Boxplot</h3>
<p>O <strong>Boxplot</strong> é um gráfico que descreve a distribuição empírica dos dados, formado pelo o 1o quartil, a mediana, o 3o quartil e hastes inferiores e superiores que delimitam as observações típicas, os pontos fora destes limites são considerados dados discrepantes ou atípicos (outliers). Os limites são calculados a partir do intervalo interquartílico.</p>
<p><span class="math display">\[Linf=q1-1,5IQR\]</span> <span class="math display">\[Lsup=q3+1,5IQR\]</span></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-boxplot" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;8: Boxplot
</figcaption>
<div aria-describedby="fig-boxplot-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-boxplot-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>O boxplot dos 40 ensaios de vidas úteis de baterias pode ser gerado com o comando <code>boxplot()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># gráficos</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(bateria<span class="sc">$</span>vida_util, </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">'Vida útil (anos)'</span>,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">las=</span><span class="dv">1</span>, </span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="st">'yellow'</span>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(xbar, <span class="at">pch=</span><span class="st">'+'</span>, <span class="at">cex=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"red"</span>) <span class="co"># Média</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-boxplot_baterias" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-boxplot_baterias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;9: Boxplot das observações de vidas úteis de baterias
</figcaption>
<div aria-describedby="fig-boxplot_baterias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-boxplot_baterias-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>O comando <code>points()</code> acrescenta o sinal “+” na posição da média, tornando o gráfico mais informativo.</p>
<p>As estatísticas utilizadas para a elaboração do boxplot podem ser acessadas. Para tanto, primeiramente, devem-se ser armazenadas num objeto que, neste exemplo, foi denominado meuBoxplot.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>meuBoxplot<span class="ot">&lt;-</span><span class="fu">boxplot</span>(bateria<span class="sc">$</span>vida_util, <span class="at">ylab=</span><span class="st">'Vida útil (anos)'</span>, <span class="at">las=</span><span class="dv">1</span>, <span class="at">col=</span><span class="st">'Yellow'</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Pode-se então exibir a lista de nomes das estatísticas armazenadas com o comando <code>names()</code>. No <code>out</code>, estão os valores dos <em>outliers</em>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(meuBoxplot)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "stats" "n"     "conf"  "out"   "group" "names"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>meuBoxplot<span class="sc">$</span>out</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.6 1.9</code></pre>
</div>
</div>
<p>Uma maneira muito simples de identificar os <em>outliers</em> no boxplot é disponibilizado pelo comando <code>Boxplot()</code> (com B maiúsculo) do pacote <code>car</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car) <span class="co"># pacote car</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">Boxplot</span>(bateria<span class="sc">$</span>vida_util,</span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab=</span><span class="st">'Vida útil (anos)'</span>,</span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">col=</span><span class="st">"yellow"</span>, </span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">las=</span><span class="dv">1</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10 31</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(xbar, <span class="at">pch=</span><span class="st">'+'</span>, <span class="at">cex=</span><span class="dv">2</span>, <span class="at">col=</span><span class="st">"red"</span>) <span class="co"># média</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-boxplot_out" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-boxplot_out-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;10: Boxplot com a identificão dos outliers
</figcaption>
<div aria-describedby="fig-boxplot_out-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-boxplot_out-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Como se pode observar nos resultados do comando <code>Boxplot</code> e pelo gráfico, os tempos do 31o e do 10o ensaios de baterias são atípicos quando comparadas com os demais.</p>
</section>
<section id="histograma" class="level3" data-number="2.4.2">
<h3 data-number="2.4.2" class="anchored" data-anchor-id="histograma"><span class="header-section-number">2.4.2</span> Histograma</h3>
<p><strong>Histogramas</strong> são gráficos de barras em que as barra representam a frequência dos dados e seus respectivos intervalos. Esses interlavos não se sobrepõem e são os gráficos que representam as tabelas de distribuição de frequências.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(bateria<span class="sc">$</span>vida_util, <span class="at">col =</span> <span class="st">"red"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-hist_bateriais" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-hist_bateriais-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;11: Histograma das observações das vidas úteis de bateriais
</figcaption>
<div aria-describedby="fig-hist_bateriais-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-hist_bateriais-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="exercício" class="level3" data-number="2.4.3">
<h3 data-number="2.4.3" class="anchored" data-anchor-id="exercício"><span class="header-section-number">2.4.3</span> Exercício</h3>
<p>Os dados da força de ruptura em libras por polegada quadrada para 100 garrafas descartáveis de 1 litro de refrigerante estão no arquivo <a href="dadosForca.R"><strong>dadosForca.R</strong></a>. Essas medidas foram obtidas, testando-se cada garrafa até ocorrer a quebra. (FONTE: HINES et al.&nbsp;(2006), Tabela 8-2, p.&nbsp;157).</p>
<p>Faça o que se pede:</p>
<ol type="a">
<li>Importe os dados. <strong>Dica:</strong> use o comando <code>load()</code>.</li>
<li>Calcule as estatísticas descritivas e gere uma tabela com essas medidas.</li>
<li>Qual o valor da média amostral?</li>
<li>Como a dispersão de dados pode ser classificada, segundo a clasificação de segundo Pimentel e Gomes (1985)?</li>
<li>Elabore um boxplot e marque a localização da média na distribuição.</li>
<li>Ao examinar o boxplot, pode-se afirmar que a distribuição é simétrica? Acrescente a assimetria medida para reforçar a análise.</li>
</ol>
</section>
</section>
</section>
<section id="probabilidades" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Probabilidades</h1>
<p>Probabilidade exprime a chance de ocorrência de um evento. A probabilidade é um número relativo aos resultados possíveis que varia de zero a 1. A ocorrência do evento é denominado <strong>sucesso</strong> e <strong>fracasso</strong> a sua não ocorrência que o complemento dos possíveis resultados.</p>
<p><span class="math display">\[P(A)= \dfrac{n_x}{n}\]</span> <span class="math display">\[0\leq P(x) \leq 1\]</span> <span class="math display">\[P(x')=1-P(x)\]</span></p>
<p><span class="math display">\[\sum_{i=1}^{n}P(x)=1\]</span> O conjunto dos possíveis resultados que se pode obter é denominado espaço amostral <span class="math inline">\(S\)</span>. Um exemplo do espaço amostral com os possíveis resultados do lançamento de duas moedas honestas (não-viciadas) é apresentado abaixo. <span class="math display">\[S=\{CC,CK,KC,KK\}\]</span></p>
<p>Observa-me que 4 resultados possíveis e a probabilidade de cada resultado é <span class="math inline">\(\frac{1}{4}=0,25\)</span></p>
<p>Qual a probabilidade do lançamento de duas moeda honestas ser uma <em>K</em> (Cara) e qual a probabilidade do resultado ser diferente de cara?</p>
<p><span class="math display">\[P(CK)+P(KC)=(0,25)+(0,25)=0,50\]</span></p>
<section id="distribuições-de-probabilidades" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="distribuições-de-probabilidades"><span class="header-section-number">3.1</span> Distribuições de probabilidades</h2>
<p>Uma distribuição de probabilidade é uma distribuição de frequências relativas para os resultados de um espaço amostral.</p>
<p>Mostra a proporção das vezes em que uma variável aleatória discreta tende a assumir cada um dos diversos valores.</p>
<p><img src="Figuras\img_moeda.png" class="img-fluid" style="width:60.0%"></p>
<p><br><br></p>
<p>A altura de cada barra indica a probabilidade de ocorrência de um evento.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-dist_freq_moedas" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-dist_freq_moedas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;12: distribuição de Probabilidade de uma cara no lançamento de duas moedas
</figcaption>
<div aria-describedby="fig-dist_freq_moedas-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-dist_freq_moedas-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="diferença-ente-distribuição-de-probabilidades-e-distribuição-de-frequências" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="diferença-ente-distribuição-de-probabilidades-e-distribuição-de-frequências"><span class="header-section-number">3.2</span> Diferença ente distribuição de probabilidades e distribuição de frequências</h2>
<p>A <strong>distribuição de probabilidade</strong> se baseia num modelo teórico e se conhece todos os possíveis valores que uma variável aleatória pode assumir enquanto que a <strong>distribuição de frequências</strong> descreve a realidade, e se conhece somente os valores observados (LEVI e FOX, 2004).</p>
<p>Observe o registro dos lançamentos de duas moedas jogadas 10 vezes. Os resultados se comportaram extamente igual aos da distribuição de probabilidades?</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  fa  fr fp f.acum
0  3 0.3 30    0.3
1  6 0.6 60    0.9
2  1 0.1 10    1.0</code></pre>
</div>
<div class="cell-output-display">
<div id="fig-dist_freq_moedas10" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-dist_freq_moedas10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;13: Distribuição de frequências de uma cara em 10 lançamentos de duas moedas
</figcaption>
<div aria-describedby="fig-dist_freq_moedas10-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-dist_freq_moedas10-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Agora veja os resultados de uma cara em 1.000 jogadas de duas moedas. A distribuição de frequências se parece mais com a distribuição de probabilidades?</p>
<p>As leis da probabilidade se tornam mais evidentes a medida em que se aproxima de um número infinito de jogadas. Logo podemos concluir que uma distribuição de probabilidade é essencialmente uma distribuição de frequências de um número infinito de jogadas, como nos explicam Levin e Fox (2004).</p>
</section>
<section id="distribuição-de-frequências-de-dados-experimentais" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="distribuição-de-frequências-de-dados-experimentais"><span class="header-section-number">3.3</span> Distribuição de frequências de dados experimentais</h2>
<p>Consideremos novamente a força de ruptura em libras por polegada quadrada para 100 garrafas descartáveis de 1 litro de refrigerante. (FONTE: HINES et al., 2006, Tabela 8-2, p.&nbsp;157). Como a medida da resposta do experimento está em unidade de psi que é uma variável quantitativa contínua, seus valores devem ser organizados em classes para apresentação em forma de tabela e gráficos, sendo o histograma o gráfico mais utilizado.</p>
<section id="criando-uma-tabela-de-distribuição-de-frequências" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="criando-uma-tabela-de-distribuição-de-frequências"><span class="header-section-number">3.3.1</span> Criando uma tabela de distribuição de frequências</h3>
<p>Tabelas de frequências para dados quantitativos contínuos exigem o agrupamento dos dados em classes.</p>
<p>O padrão mais comum, são intervalos de classe fechado a esquerda (incluso) e abertos a direita (não incluso), o valor à esquerda pertence aquele intervalo enquanto que o da direita não pertence.O exemplo, um intervalo de 10 a 20, O 10 pertence ao intervalo, enquanto o 20 não. Se 20 existe, está no próximo intervalo de classe, podendo ser representado das seguintes maneiras.</p>
<p><span class="math display">\[10\vdash20\]</span> <span class="math display">\[10\leq x&lt;20\]</span> <span class="math display">\[[10,20[\]</span> <span class="math display">\[[10,20)\]</span></p>
<p>O número de intervalos de classe (<span class="math inline">\(k\)</span>) pode ser determinado a partir de um critério, sendo que o <strong>critério da raiz</strong> e o <strong>critério de Sturgles</strong>.</p>
<p>Critério da Raiz</p>
<p><span class="math display">\[
\left\{ \begin{array}{l}
\text{Se} \; n&lt;25,\;k=5 \\
\text{Se} \; n \geq25,\;k\cong\sqrt{n}
\end{array}\right.
\]</span></p>
<p>Critério de Sturgles <span class="math display">\[k\cong1+3,32\log n\]</span> Amplitude de classe (<span class="math inline">\(h\)</span>)</p>
<p><span class="math display">\[h=\frac{A}{k}\]</span></p>
<p>Para elaborar a tabela de frequência para os dados da força de ruptura em libras por polegada quadrada para 100 garrafas descartáveis de 1 litro de refrigerante, inicia-se com o exame preliminar dos dados, dos valores mínimos e máximos, seguindo para a determinadação do número de classes (<em>k</em>) e da amplitude de classes (<em>h</em>)</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">"dadosForca.R"</span>)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(dadosForca) <span class="co"># Exame preliminar dos objeto e dados</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   100 obs. of  1 variable:
 $ forca: int  265 205 263 307 220 268 260 234 299 215 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a><span class="co"># View(dadosForca) # exibe dados</span></span>
<span id="cb28-2"><a href="#cb28-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb28-3"><a href="#cb28-3" aria-hidden="true" tabindex="-1"></a><span class="fu">length</span>(dadosForca<span class="sc">$</span>forca)          <span class="co"># no de obs.</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 100</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(dadosForca<span class="sc">$</span>forca)           <span class="co"># minimo e maximo</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 176 346</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sqrt</span>(<span class="fu">length</span>(dadosForca<span class="sc">$</span>forca))    <span class="co"># no classes criterio Raiz</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a><span class="fu">nclass.Sturges</span>(dadosForca<span class="sc">$</span>forca)  <span class="co"># no classes criterio Sturges 1+3.3*log10(n)</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 8</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">diff</span>(<span class="fu">range</span>(dadosForca<span class="sc">$</span>forca, <span class="at">na.rm=</span>T))<span class="sc">/</span><span class="fu">sqrt</span>(<span class="fu">length</span>(dadosForca<span class="sc">$</span>forca)) <span class="co"># Amplitude classe (raiz)</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">diff</span>(<span class="fu">range</span>(dadosForca<span class="sc">$</span>forca, <span class="at">na.rm=</span>T))<span class="sc">/</span><span class="fu">nclass.Sturges</span>(dadosForca<span class="sc">$</span>forca) <span class="co"># Amplitude classe (Stargle)</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 21.25</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="dv">170</span><span class="sc">+</span><span class="dv">9</span><span class="sc">*</span><span class="dv">20</span> <span class="co"># minimo + 5 intervalos de 20 cada</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 350</code></pre>
</div>
</div>
<p>Caso se deseje um limite inferior para a primeira classe redondo e ligeiramente inferior a valor mínimo dos dados, pode-se inicar em 170 para 9 classes com intervalo de 20 unidades de psi, o que cobriria os valore até 350, incluindo o valor máximo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>bins <span class="ot">&lt;-</span> <span class="fu">seq</span>(<span class="at">from =</span> <span class="dv">170</span>, <span class="at">to =</span> <span class="dv">350</span>, <span class="at">by=</span><span class="dv">20</span>)</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>scores <span class="ot">&lt;-</span> <span class="fu">cut</span>(dadosForca<span class="sc">$</span>forca, bins, <span class="at">right=</span><span class="cn">FALSE</span>)</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>fa <span class="ot">&lt;-</span> <span class="fu">table</span>(scores)</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>fr <span class="ot">&lt;-</span> <span class="fu">prop.table</span>(fa)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>tb.dist <span class="ot">&lt;-</span> <span class="fu">transform</span>(fa, </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">FreqRel =</span> <span class="fu">prop.table</span>(Freq)<span class="sc">*</span><span class="dv">100</span>,</span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>                     <span class="at">FreqAcum =</span> <span class="fu">cumsum</span>(Freq),</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a>                     <span class="at">FreqRelAcum =</span> <span class="fu">cumsum</span>(<span class="fu">prop.table</span>(Freq)<span class="sc">*</span><span class="dv">100</span>))</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>tb.dist</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>     scores Freq FreqRel FreqAcum FreqRelAcum
1 [170,190)    2       2        2           2
2 [190,210)    4       4        6           6
3 [210,230)    7       7       13          13
4 [230,250)   13      13       26          26
5 [250,270)   32      32       58          58
6 [270,290)   24      24       82          82
7 [290,310)   11      11       93          93
8 [310,330)    4       4       97          97
9 [330,350)    3       3      100         100</code></pre>
</div>
</div>
<p>Determinado que <span class="math inline">\(k=9\)</span> e <span class="math inline">\(h=20\)</span>, gera-se a seguência de intervalos (<em>bins</em> = caixa em inglês) determndados pelas pontes de quebra. Depois os dados são classificados, ou cortados, em cada classe (<em>bins</em>) como o comando <code>cut()</code>, crinado assim um novo score. Com os comando <code>table()</code>, cria-se uma tabela de frequências absolutas, e, com o comando <code>prop.table</code>, uma tabela de frequências relativas.</p>
<p>Para uma tabela de frequência personalizada, os recursos do comando <code>transform()</code> são muito convenientes por permitir o cálculo das colunas a partir dos valores da coluna inicial que será justamente a tabela de frequências acumuladas já criada previamente. A tabela resultante é esteticamente atraente e permite uma manipulação posterior fácil por ser um data.frame.</p>
<p>Caso se deseje criar uma tabela com a classes iguais ao padrão dos histogramas do R.</p>
</section>
<section id="criando-um-histograma" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="criando-um-histograma"><span class="header-section-number">3.3.2</span> Criando um histograma</h3>
<p>O histograma pode ser criado automaticamente como o comando <code>hist()</code> e personalizado, ajustando seus vários argumentos. O argumento <code>right=FALSE</code>, ajuste os intervalos a serem fechados a esquerda e abertos à direita, apesar que em distribuições com muitos dados, como esta, isso não faça muita diferença, mas será importante para casos com poucos dados ou quando a primeira classe incia no valor mínimo ou última se termina no valor máximo dos dados.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dadosForca<span class="sc">$</span>forca,</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">right =</span> <span class="cn">FALSE</span>, </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"chocolate"</span>,</span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">border =</span> <span class="st">"brown"</span>,</span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">""</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-hist_base_col" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-hist_base_col-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;14: Histograma com No e intervalos de classes sugeridos pelo R
</figcaption>
<div aria-describedby="fig-hist_base_col-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-hist_base_col-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Para se obter os parâmetros do histograma padrão do R, basta o salvar num objeto e exibir, como demonstraado abaixo:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>meuHist<span class="ot">&lt;-</span><span class="fu">hist</span>(dadosForca<span class="sc">$</span>forca,<span class="at">right =</span> <span class="cn">FALSE</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(meuHist)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "breaks"   "counts"   "density"  "mids"     "xname"    "equidist"</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>meuHist<span class="sc">$</span>breaks <span class="co"># Limites das classes</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 160 180 200 220 240 260 280 300 320 340 360</code></pre>
</div>
</div>
</section>
<section id="criando-histogramas-personalizados" class="level3" data-number="3.3.3">
<h3 data-number="3.3.3" class="anchored" data-anchor-id="criando-histogramas-personalizados"><span class="header-section-number">3.3.3</span> Criando histogramas personalizados</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>par.copy<span class="ot">&lt;-</span><span class="fu">par</span>() <span class="co"># guarda default</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">bg=</span><span class="st">"grey90"</span>)</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dadosForca<span class="sc">$</span>forca, </span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">breaks =</span> <span class="fu">c</span>(bins),</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">right =</span> <span class="cn">FALSE</span>, </span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">col=</span><span class="st">"steelblue"</span>,</span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>     <span class="at">border=</span><span class="st">"white"</span>,</span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>     <span class="at">xaxt=</span><span class="st">"n"</span>,</span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="fu">expression</span>(lbf<span class="sc">/</span>pol<span class="sc">^</span><span class="dv">2</span>),</span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>     <span class="at">main=</span><span class="st">""</span>)</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a><span class="fu">axis</span>(<span class="dv">1</span>, <span class="at">at=</span><span class="fu">c</span>(bins), </span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels=</span>bins, </span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>     <span class="at">tck=</span><span class="dv">0</span>,</span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>     <span class="at">las=</span><span class="dv">1</span>,</span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>     <span class="at">lty=</span><span class="dv">0</span>,</span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>     <span class="at">line=</span><span class="sc">-</span><span class="dv">1</span>,</span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a>     <span class="at">cex.axis=</span><span class="dv">1</span>)</span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-21"><a href="#cb50-21" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(par.copy) <span class="co"># Reestabelece as configuracoes originais</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-hist_personalizado" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-hist_personalizado-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;15: Histograma Personalizado
</figcaption>
<div aria-describedby="fig-hist_personalizado-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-hist_personalizado-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>No histograma a seguir, há duas novidades. O uso de tons vermelhos para as nove colunas e a utilização dos intervalos em substituição aos limites de classe no rótulos do eixo de x com uma inclinação de 45<span class="math inline">\(^O\)</span>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(RColorBrewer) <span class="co"># pacote de Cores</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>cols<span class="ot">&lt;-</span><span class="fu">brewer.pal</span>(<span class="dv">9</span>,<span class="st">"Reds"</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(dadosForca<span class="sc">$</span>forca, <span class="at">breaks =</span> <span class="fu">c</span>(bins),<span class="at">right =</span> F, <span class="at">col=</span>cols, <span class="at">xaxt=</span><span class="st">"n"</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co">#axis(1, at=c(bins[-10]+20/2), labels=tb.dist$scores,tck=0,line=-1, las=1, lty=0,cex.axis=.7)</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(bins[<span class="sc">-</span><span class="dv">10</span>]<span class="sc">+</span><span class="dv">20</span><span class="sc">/</span><span class="dv">2</span>,<span class="fu">par</span>(<span class="st">"usr"</span>)[<span class="dv">3</span>],  </span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> tb.dist<span class="sc">$</span>scores, <span class="at">srt =</span> <span class="dv">45</span>, <span class="at">pos =</span> <span class="dv">2</span>, <span class="at">xpd =</span> <span class="cn">TRUE</span>, <span class="at">cex=</span>.<span class="dv">8</span> )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-hist_inclinado" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-hist_inclinado-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;16: Histograma com paleta e rótulos inclinados
</figcaption>
<div aria-describedby="fig-hist_inclinado-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-hist_inclinado-1.png" class="img-fluid figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>O pacote <code>RColorBrewer()</code> disponibiliza vários esquemas de tons de cores. Para exibi-los digite <code>display.brewer.all()</code>. Para personalizar o gráfico, o histograma é inicialmente gerado sem os eixo horizontal, argumento <code>xaxt="n"</code>. Usam-se os valores das classe armazenadas na coluna socres do objeto <strong>tb.dist</strong> para os rótulos, <code>labels = tb.dist$scores</code>.</p>
<!-- 
http://sphaerula.com/legacy/R/placingTextInPlots.html
-->
</section>
<section id="exercício-1" class="level3" data-number="3.3.4">
<h3 data-number="3.3.4" class="anchored" data-anchor-id="exercício-1"><span class="header-section-number">3.3.4</span> Exercício</h3>
<ol type="a">
<li>Elabore uma tabela de frequência para os dados dos experimentos de tempo de vida útil de baterias em anos que estão no documento “<strong>bateria.RData</strong>”; posteriormente um histograma personalizado a partir de sua tabela e o compare com o histograma gerado automaticamente pelo R.</li>
<li>Elabore uma tabela de frequência para os dados dos experimentos de tempo de vida útil de baterias em anos que estão no documento “<strong>bateria.RData</strong>”, utilizando os limites de classe do comando <code>hist()</code>. <strong>Dica:</strong> Salve o histograma num objeto. Os limites de classe estarão armazenados nos valores de <code>$breaks</code> desse objeto.</li>
</ol>
</section>
</section>
<section id="densidade" class="level2" data-number="3.4">
<h2 data-number="3.4" class="anchored" data-anchor-id="densidade"><span class="header-section-number">3.4</span> Densidade</h2>
<p>A <strong>densidade</strong>, numa distribuição contínua, é a medida de probabilidade de se obter um número próximo a <span class="math inline">\(x\)</span>. Para distribuições discretas, a densidade é a probabilidade de obter exatamente um determinado valor, já que corresponde a uma contagem.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-graus" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-graus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;17: Roleta de graus
</figcaption>
<div aria-describedby="fig-graus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/img_graus.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>roleta<span class="ot">&lt;-</span><span class="fu">seq</span>(<span class="at">from=</span><span class="dv">0</span>, <span class="at">to=</span><span class="dv">360</span>,<span class="at">by=</span><span class="dv">1</span>)</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a><span class="fu">range</span>(roleta)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1]   0 360</code></pre>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-prob_graus" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-prob_graus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;18: Probabilidade de graus
</figcaption>
<div aria-describedby="fig-prob_graus-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/probRoleta1.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
</figure>
</div>
</div>
</div>
<p><span class="math inline">\(f(x)\)</span> é a densidade. <span class="math display">\[f(x)=\frac{1}{360}\]</span></p>
<p><span class="math display">\[P[90\leq X \leq 180]= \int_{90}^{180} f(x)dx=\int_{90}^{180} \frac{1}{360} dx=0.25\]</span></p>
</section>
</section>
<section id="a-distribuição-normal" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> A distribuição Normal</h1>
<section id="a-características-da-curva-normal" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="a-características-da-curva-normal"><span class="header-section-number">4.1</span> A características da curva normal</h2>
<ol type="1">
<li>Forma de sino;</li>
<li>Unimodal;</li>
<li>Simétrica em relação à média;</li>
<li>Prolonga-se de <span class="math inline">\(-\infty\)</span> a <span class="math inline">\(+\infty\)</span>;</li>
<li>Especificada pela média e DP e há uma curva normal para cada combinação de média e DP;</li>
<li>Área total 100%;</li>
<li>Área entre a média e um ponto arbitrário é função do número dos desvios padrões entre a média e aquele ponto.</li>
</ol>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-dist_normal" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-dist_normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;19: Distribuição (Curva) Normal
</figcaption>
<div aria-describedby="fig-dist_normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-dist_normal-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-dist_qi" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-dist_qi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;20: Distribuição de QI
</figcaption>
<div aria-describedby="fig-dist_qi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-dist_qi-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-area_curva_direto" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-area_curva_direto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;21: Área do lado direito da curva normal
</figcaption>
<div aria-describedby="fig-area_curva_direto-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-area_curva_direto-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-area_curva" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-area_curva-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;22: Área total sob a curva normal
</figcaption>
<div aria-describedby="fig-area_curva-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-area_curva-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="a-curva-normal-padronizada" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="a-curva-normal-padronizada"><span class="header-section-number">4.2</span> A Curva Normal Padronizada</h2>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-curvas_normais" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-curvas_normais-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;23: Curvas Normais
</figcaption>
<div aria-describedby="fig-curvas_normais-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-curvas_normais-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-curva_pad" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-curva_pad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;24: Curva Normal Padronizada
</figcaption>
<div aria-describedby="fig-curva_pad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-curva_pad-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="escores-padronizados" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="escores-padronizados"><span class="header-section-number">4.3</span> Escores padronizados</h2>
<p><span class="math display">\[z=\frac{x_i-\bar{x}}{\sigma}\]</span></p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-prob_dist_qi_z" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-prob_dist_qi_z-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;25: Distribuição de QI e os valores padronizados
</figcaption>
<div aria-describedby="fig-prob_dist_qi_z-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-prob_dist_qi_z-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="distribuição-t" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="distribuição-t"><span class="header-section-number">4.4</span> Distribuição <em>t</em></h2>
<p>Quando o desvio padrão <span class="math inline">\(\sigma\)</span> é desconhecido e substituido por sua estimativa <span class="math inline">\(s\)</span>, os valores padronizados deixam de seguir a distribuição normal padronizada devido ao pertubação provocada pela incerteza. William Sealy Gosset, sob o pseudônimo “Student” derivou o que que ficou conhecido como distribuição t, muito útil em pequenas amostras.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-t_normal" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-t_normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;26: Comparação entre a curva padrão e distribuição t com 3 gl
</figcaption>
<div aria-describedby="fig-t_normal-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-t_normal-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>A distribuição t se trata de uma família de distribições descritas pelos graus de liberdade (gl). Os gl são definidos como <span class="math inline">\(n-1\)</span>, na qual <span class="math inline">\(n\)</span> é o número de observações da amostra.</p>
<p><span class="math display">\[t=\frac{\bar{x}-\mu}{\dfrac{s}{\sqrt{n}}}=\frac{\bar{x}-\mu}{ep}\]</span></p>
<p>onde a variável <span class="math inline">\(t\)</span> tem distribuição <em>t</em> de Student com <span class="math inline">\(n-1\)</span> graus de liberdade.</p>
</section>
<section id="a-estimativa" class="level2" data-number="4.5">
<h2 data-number="4.5" class="anchored" data-anchor-id="a-estimativa"><span class="header-section-number">4.5</span> A Estimativa</h2>
<ul>
<li><strong>Estimativa pontual</strong>: estimativa única de um parâmetro.</li>
<li><strong>Estimativa Intervalar</strong>: O intervalo de valores possíveis no qual se admite esteja o parâmetro populacional.
<ul>
<li>Em virtude da variabilidade, é comum acompanhar a estimativa pontual.</li>
</ul></li>
</ul>
<p>Exemplos de estimativas</p>
<table class="caption-top table">
<colgroup>
<col style="width: 15%">
<col style="width: 42%">
<col style="width: 42%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: center;">parâmetro</th>
<th>Pontual</th>
<th>Intervalar</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">Média</td>
<td>Um brasileiro médio bebe 12l de leite/ano</td>
<td>O consumo médio de leite no país está entre 8 a 16 litros</td>
</tr>
<tr class="even">
<td style="text-align: center;">Proporção</td>
<td>A proporção de estudantes fumantes é de 43%</td>
<td>A proporção de estudantes fumantes está entre 37% a 49%</td>
</tr>
</tbody>
</table>
<section id="o-conceito-de-intervalo-de-estimação" class="level3" data-number="4.5.1">
<h3 data-number="4.5.1" class="anchored" data-anchor-id="o-conceito-de-intervalo-de-estimação"><span class="header-section-number">4.5.1</span> O conceito de intervalo de estimação</h3>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ic_conceito" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-ic_conceito-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;27: População e amostra
</figcaption>
<div aria-describedby="fig-ic_conceito-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/img_ic_conceito.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
</figure>
</div>
</div>
</div>
<blockquote class="blockquote">
<p>Independentemente do nível de confiança que adotemos, ainda não podemos dizer se determinada média amostral é menor, ou maior, do que o valor desconhecido populacional. Como não há maneira de saber ao certo, admitimos o pior e construimos um intervalo de valores verdadeiros possíveis.</p>
<p>– <cite>STEVENSON, p.&nbsp;196-197</cite></p>
</blockquote>
<blockquote class="blockquote">
<p>statistical analyses are about creating confidence based on evidence</p>
<p>– <cite>Wobbrock (University of Washington)</cite></p>
</blockquote>
</section>
<section id="intervalo-de-confiança" class="level3" data-number="4.5.2">
<h3 data-number="4.5.2" class="anchored" data-anchor-id="intervalo-de-confiança"><span class="header-section-number">4.5.2</span> Intervalo de confiança</h3>
<ul>
<li><strong>Intervalo de confiança</strong>: intervalo de valores, centrado na estatística amostral, no qual se espera estar o parâmetro populacional, com risco conhecido de erro.</li>
<li>Para a determinação do intertelo no qual deve estar o pâmetro populacional, é necessário a estimação de duas estatísticas, o limite inferior (LI) e o limite superior do intervalo (LS).</li>
<li><strong>Erro de estimação</strong>: diferença (desvio) entre a média amostral e a verdadeira média populacional.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-ic.png" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-ic.png-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;28: Intervalo de confiança
</figcaption>
<div aria-describedby="fig-ic.png-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="Figuras/img_ic.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
</figure>
</div>
</div>
</div>
<p><span class="math display">\[IC=\bar{x}\pm erro\]</span></p>
<p><span class="math display">\[erro=t_{n-1}ep\]</span></p>
<p><span class="math display">\[ep=\dfrac{s}{\sqrt{n}}\]</span> <span class="math display">\[IC=\bar{x}\pm t_{n-1}\dfrac{s}{\sqrt{n}}\]</span> onde <span class="math inline">\(t_{n-1}\)</span> é o valor tabelado (ou quartil) da distribuição <em>t</em> de Student com <span class="math inline">\(\nu=n-1\)</span> graus de liberdade para o valor do nível de significância (<span class="math inline">\(\alpha\)</span>) fixado. O valor tabelado de <em>t</em> pode se obtido, usando-se o comando <code>qt(p, df)</code>, em que <code>p</code> é a probabilidade acumulada ou nível de confiança e <code>df</code> são os graus de liberdade (<em>degrees of freedom</em>).</p>
<p>No exemplo da vida útil das baterias, em que há 40 ensaios (<span class="math inline">\(n=40\)</span>), o número de graus de liberdade é <span class="math inline">\(\nu=40-1=39\)</span> e o valor <em>t</em> tabelado para intervalo de confiança de 95% e nível significância de <span class="math inline">\(5\%\)</span> são calculados a seguir, lembrando que o IC se distribui igualmante nos dois lados, <span class="math inline">\(\frac{\alpha}{2}\)</span> .</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df=</span><span class="dv">39</span>) <span class="co">#t-tab., IC= 97.5%, alfa=5%/2=2.5%, n-1=39, positivo</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.022691</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span> (<span class="fl">0.025</span>, <span class="at">df=</span><span class="dv">39</span>)<span class="co">#t-tab., IC= 95%(2.5%), alfa=5%/2=2.5%, n-1=39, negativo</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.022691</code></pre>
</div>
</div>
<p>Agora, vamos calcular o intervalo de confiança para um nível de confiança de 95%, <span class="math inline">\(\alpha=0,05\)</span>. Como se trata de um teste bilateral.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Intervalo de conf. (Estivativa intervalar)</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(bateria<span class="sc">$</span>vida_util) <span class="co"># No de obs.</span></span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>xbar <span class="ot">&lt;-</span> <span class="fu">mean</span>(bateria<span class="sc">$</span>vida_util) <span class="co"># media</span></span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>s <span class="ot">&lt;-</span> <span class="fu">sd</span>(bateria<span class="sc">$</span>vida_util)  <span class="co"># desvio-padrão</span></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>ep <span class="ot">&lt;-</span> s<span class="sc">/</span><span class="fu">sqrt</span>(n)  <span class="co"># erro-padrão</span></span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>alfa <span class="ot">&lt;-</span> <span class="fl">0.05</span><span class="sc">/</span><span class="dv">2</span>   <span class="co"># distribuido nos dois lados</span></span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>conf <span class="ot">&lt;-</span> <span class="dv">1</span><span class="sc">-</span>alfa</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>erro<span class="ot">&lt;-</span><span class="fu">qt</span>(conf, <span class="at">df=</span>n<span class="dv">-1</span>)<span class="sc">*</span>ep</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>Linf <span class="ot">&lt;-</span> xbar<span class="sc">-</span>erro</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>Lsup <span class="ot">&lt;-</span> xbar<span class="sc">+</span>erro</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a><span class="fu">cbind</span>(Linf, xbar, Lsup)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>        Linf   xbar    Lsup
[1,] 3.18773 3.4125 3.63727</code></pre>
</div>
</div>
<p><strong>Interpretação</strong>: O método utilizado produz um intervalo de confiança que contém o verdadeiro valor do parâmetro 95% das vezes.</p>
</section>
</section>
</section>
<section id="teste-de-hipóteses" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Teste de hipóteses</h1>
<p>Hines, et al.&nbsp;(2011) explicam que, no contexto estatístico, uma hipótese é uma afirmativa sobre a distribuição probabilística de uma variável aleatória, envolvendo um ou mais de seus parâmetros e o teste de hipótese é o procedimento em que decise se essa afirmativa (ou hipótese) é verdadeira.</p>
<ul>
<li>Finalidade: avaliar afirmações sobre o valores dos parâmetros populacionais</li>
<li>A diferença pode ser razoavelmente atribuído à variabilidade amostral ou à discrepância é demasiada grande para ser encarada assim.</li>
<li><strong>hipóteses</strong>: Explicações, afirmações (teorias) a respeito de algo.
<ul>
<li>hipótese Nula (<span class="math inline">\(H_0\)</span>)
<ul>
<li>não há diferenças entre grupos</li>
<li>não há alteração</li>
<li>a média, mediana ou número de observações é igual algum valor</li>
</ul></li>
<li>hipótese Alternativa (<span class="math inline">\(H_1\)</span>)
<ul>
<li>há diferenças entre grupos</li>
<li>há alteração</li>
<li>a média, mediana ou número de observações é menor, maior ou diferente a algum valor</li>
</ul></li>
</ul></li>
<li>possíveis conclusões
<ul>
<li>Rejeitar <span class="math inline">\(H_0\)</span>, a hipótese é falsa.</li>
<li>não rejeitar (aceitar) <span class="math inline">\(H_0\)</span>.</li>
</ul></li>
</ul>
<p>Por exemplo, um fabricante pode afirmar que a duração média de suas baterias é de 3,5 anos. Esse tempo de vida útil é uma hipótese a ser testada.</p>
<p><span class="math display">\[H_0:\mu=3,5\text{ anos}\]</span> <span class="math display">\[H_1:\mu \neq 3,5\text{ anos}\]</span></p>
<blockquote class="blockquote">
<p>as hipóteses são sempre afirmativas sobre a população ou distribuição em estudo, não afirmativas sobre a amostra.</p>
<p>– <cite>Hines, et al.&nbsp;(2011), p.&nbsp;238</cite></p>
</blockquote>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-h_bi" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-h_bi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;29: Teste de hipótese bicaudal
</figcaption>
<div aria-describedby="fig-h_bi-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-h_bi-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-h_un_esquerda-1" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-h_un_esquerda-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;30: Teste de hipótese unicaudal à esquerda
</figcaption>
<div aria-describedby="fig-h_un_esquerda-1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-h_un_esquerda-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
<div class="cell-output-display">
<div id="fig-h_un_esquerda-2" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-h_un_esquerda-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;31: Teste de hipótese unicaudal à esquerda
</figcaption>
<div aria-describedby="fig-h_un_esquerda-2-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-h_un_esquerda-2.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<section id="tipos-de-erros-em-um-teste-de-hipóteses" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="tipos-de-erros-em-um-teste-de-hipóteses"><span class="header-section-number">5.1</span> Tipos de erros em um teste de hipóteses</h2>
<p align="center">
<img src="figuras\errosTipo.png" class="img-fluid" style="width:40.0%">
</p>
<p>Tendo em vista que o teste de hipóteses é baseado em estatísticas amostrais, as decisões são sujeitas a erros de dois tipos.</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-erro_tipo.png" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-erro_tipo.png-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;32: Tipos de erros
</figcaption>
<div aria-describedby="fig-erro_tipo.png-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figuras/img_erro_tipo.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
</figure>
</div>
</div>
</div>
<ul>
<li><p>O <strong>erro tipo I</strong> é a rejeição da hipótese nula quando ela é verdadeira, também denominado <strong>falso positivo</strong>. A probabilidade de cometê-lo é denominado <em>nível de significância</em> (<span class="math inline">\(\alpha\)</span>) ou <em>tamanho do teste</em>. <span class="math display">\[\alpha=P(H_0\text{ é rejeitada }|H_0\text{ é verdeira})\]</span></p></li>
<li><p>O <strong>erro tipo II</strong> é a não rejeição da hipótese nula quando ela é falsa, também denominado <strong>falso negativo</strong>. A probabilidade de cometê-lo é chamada de <span class="math inline">\(\beta\)</span>. (<span class="math inline">\(1-\beta\)</span>) é denominado <em>poder do teste</em> e indica a probabilidade de se não cometer o erro do tipo II, logo o poder do teste é a probabilidade de se rejeitar corretamente <span class="math inline">\(H_0\)</span> <span class="math display">\[\beta=P(H_0\text{ é aceita }|H_0\text{ é falsa})\]</span></p></li>
</ul>
<p>Em virtude das dados serem amostrais, a informação disponível é incompleta; logo, não é possível <span class="math inline">\(\alpha=0\)</span> nem <span class="math inline">\(\beta=0\)</span>. Como <span class="math inline">\(\alpha=0\)</span> é controlada pela localização da zona crítica que pode ser determinada pelo tomador de decisão, na prática, análise se concentra no erro tipo I, ou seja, na definição do nível de significância, <span class="math inline">\(\alpha\)</span>.</p>
</section>
<section id="valor-p-e-alfa" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="valor-p-e-alfa"><span class="header-section-number">5.2</span> Valor P e alfa</h2>
<p>O valor-p pode ser definido como o nível de significância exato “de a hipótese nula ser verdadeira à luz dos dados amostrais” (LEVIN; FOX, 2004, p.&nbsp;234), ou, como definem Krishnaiah e Shahabudeen (2012), é o menor nível de significância (<span class="math inline">\(\alpha\)</span>) abaixo da qual a hipótese nula é rejeitada.</p>
<ul>
<li>Se o valor-p for <span class="math inline">\(\geq\alpha\)</span>, não se rejeita <span class="math inline">\(H_0\)</span>.</li>
<li>Se o valor-p for <span class="math inline">\(&lt;\alpha\)</span>, rejeita-se <span class="math inline">\(H_0\)</span>.</li>
<li>Geralmente, rejeita-se <span class="math inline">\(H_0\)</span> quando Valor-P <span class="math inline">\(&lt;0,05\)</span>.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-valor_p" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-valor_p-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;33: Interpretação gráfica do Valor P
</figcaption>
<div aria-describedby="fig-valor_p-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-valor_p-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<p>Na Figura acima, o valor P é menor do que o valor crítico calculado para o nível de significância. Suponhamos que <span class="math inline">\(\alpha=0.05\)</span> ou 5% e o valor-P seria menor, digamos <span class="math inline">\(p=0.02\)</span>, ou 2%, isso indica que somente teríamos rejeitado <span class="math inline">\(H_0\)</span> se o nosso teste tivesse sido mais rigoroso. Só rejeitaríamos <span class="math inline">\(H_0\)</span> se <span class="math inline">\(\alpha\)</span> fosse menor do que 2%, mas não é o caso já que decidimos por <span class="math inline">\(\alpha=5\%\)</span>. Quando <span class="math inline">\(p&lt;\alpha\)</span>, dizemos que a estatística é significante.</p>
<p>Um detalhe interessanto sobre a forma de reportar o valor-P em trabalhos científicos é que normalmente não se informa seu valor exato como nos resultados dos pacotes estatísticos, porque o que interesse é seu foi menor ou não do que <span class="math inline">\(\alpha\)</span> para que se termine a significância do teste. Logo o que se observa nos artigos mais recentes na literatura internacional é a seguinte notação:</p>
<p><span class="math display">\[p&lt;.05\]</span> <span class="math display">\[p&lt;.01\]</span> <span class="math display">\[p&lt;.001\]</span></p>
<p>Todavia quando <span class="math inline">\(p&gt;.05\)</span>, reporta-se somente <span class="math inline">\(n.s.\)</span>, do inglês <em>non-significant</em>.</p>
</section>
<section id="teste-de-hipótese-para-uma-amostra-variância-desconhecida" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="teste-de-hipótese-para-uma-amostra-variância-desconhecida"><span class="header-section-number">5.3</span> Teste de hipótese para uma amostra (variância desconhecida)</h2>
<p>Pode ocorrer que se esteja interessado em determinar se um atributo de uma amostra experimental é ou não igual a certo valor.</p>
<p><span class="math display">\[
\begin{array}{llcc}
H_0&amp;: \mu=\mu_0&amp; &amp;  \\
H_{1\textrm{(possíveis)}}&amp;:\mu\neq\mu_0, &amp; \mu&gt;\mu_0 \; \text{ou} &amp; \mu&lt;\mu_0
\end{array}
\]</span></p>
<p>onde <span class="math inline">\(\bar{x}\)</span> é a média amostral e <span class="math inline">\(\mu_0\)</span> é uma constante.</p>
<section id="exemplo" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="exemplo"><span class="header-section-number">5.3.1</span> Exemplo</h3>
<p>Após o registro de 40 ensaios (ou observações) do tempo de vida útil em anos de baterias, pretende-se decidir se a duração média é de 3,5 anos.</p>
<p><span class="math display">\[H_0:\mu=3,5\]</span> <span class="math display">\[H_0:\mu\neq3,5\]</span></p>
<p>O teste mais comum para esse tipo de situação é o teste <em>t</em>, que supõe que <span class="math inline">\(x\)</span> é uma variável aleatória normalmente distribuída com média <span class="math inline">\(\mu\)</span> e <span class="math inline">\(\sigma\)</span> desconhecidos. Como, na maioria das vezes, não se conhece a variância da população, a distribuição <em>t</em> amostral é a seguinte:</p>
<p><span class="math display">\[t_0=\frac{\bar{x}-\mu_0}{\dfrac{s_x}{\sqrt{n}}}\]</span></p>
<p>onde <span class="math inline">\(\mu_0\)</span> é o valor alegado, <span class="math inline">\(n\)</span> é o número de observações e <span class="math inline">\(s_x\)</span> é o desvio padrão da amostra. Para a hipótese bilateral, rejeita-se a <span class="math inline">\(H_0\)</span> quando <span class="math inline">\(t_0\)</span> excede o valor crítico <span class="math inline">\(t_{\frac{\alpha}{2}, n-1}\)</span>, a um nível de significância <span class="math inline">\(\alpha\)</span> com <span class="math inline">\(\nu = n-1\)</span> graus de liberdade. Já para um teste unilateral, rejeita-se <span class="math inline">\(H_0\)</span>, quando <span class="math inline">\(t_0\)</span> excede o valor <span class="math inline">\(t_{\frac{\alpha}{2}, n-1}\)</span> positivo ou negativo conforme o teste se refere à verificação do valor amostral ser maior ou menor do que o valor alegado.</p>
</section>
<section id="procedimentos" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="procedimentos"><span class="header-section-number">5.3.2</span> Procedimentos</h3>
<ol type="1">
<li>Verificar suposições: normalidade (realizada excepcionalmente adiante)</li>
<li>Fixar a <span class="math inline">\(H_0\)</span> e a <span class="math inline">\(H_1\)</span>;</li>
<li>Fixar o nível de significância <span class="math inline">\(\alpha\)</span> do teste;</li>
<li>Identificar o valor crítico <span class="math inline">\(t_{\frac{\alpha}{2}, \nu}\)</span>, num teste bilateral, para <span class="math inline">\(\nu = n-1\)</span> graus de liberdade, ou <span class="math inline">\(t_{\alpha, \nu}\)</span>, para um teste unilateral;</li>
<li>Calcular <span class="math inline">\(t_0\)</span>.</li>
<li>Decidir. Para um teste bicaudal, rejeita-se <span class="math inline">\(H_0\)</span> se <span class="math inline">\(-t_{\frac{\alpha}{2}, \nu}&gt;t_0&gt;t_{\frac{\alpha}{2}, n-1}\)</span>, ou melhor, <span class="math inline">\(|t_0|&gt;t_{\frac{\alpha}{2}, \nu}\)</span>. Caso se opte pela abordagem do valor-P, rejeita-se <span class="math inline">\(H_0\)</span> se o valor-P for inferior ao valor <span class="math inline">\(\alpha\)</span> de significância do teste. Pode-se ainda verificar se o zero faz parte do intervalo de confiança da diferença, no caso negativo é porque a diferença zero não é provável, rejeitando-se <span class="math inline">\(H_0\)</span>.</li>
</ol>
<p>Neste primeiro exemplo, deixaremos as suposição de normalidade para o final. Iniciamos carregando o arquivo baterias, inspecionando seus dados e analisando a suas estatísticas descritivas mais básicas com o comando <code>summary()</code>.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co">#load(file="bateria.RData")</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(bateria)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>  vida_util
1       2.2
2       4.1
3       3.5
4       4.5
5       3.2
6       3.7</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(bateria)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   40 obs. of  1 variable:
 $ vida_util: num  2.2 4.1 3.5 4.5 3.2 3.7 3 2.6 3.4 1.6 ...</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(bateria)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>   vida_util    
 Min.   :1.600  
 1st Qu.:3.100  
 Median :3.400  
 Mean   :3.413  
 3rd Qu.:3.825  
 Max.   :4.700  </code></pre>
</div>
</div>
<p>No <em>R</em>, o problema pode ser resolvido com a função <code>t.test()</code> que possui a seguinte sintaxe básica:</p>
<pre><code>t.test(x, mu)</code></pre>
<p>onde <em>x</em> é um vetor com os dados e <em>mu</em> média alegada, o <em>default</em> de <em>mu</em> é 0. Aplicando ao exemplo em que queremos saber se a média da vida útil das bateria é 3,5 anos executamos o comamdo da seguinte maneira:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bateria<span class="sc">$</span>vida_util, <span class="at">alternative =</span> <span class="st">"two.sided"</span>, <span class="at">mu=</span><span class="fl">3.5</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  bateria$vida_util
t = -0.78741, df = 39, p-value = 0.4358
alternative hypothesis: true mean is not equal to 3.5
95 percent confidence interval:
 3.18773 3.63727
sample estimates:
mean of x 
   3.4125 </code></pre>
</div>
</div>
<p><span class="math inline">\(H_0\)</span> <strong>não deve ser rejeitada</strong> como se pode observar de duas maneiras:</p>
<ul>
<li>O valor-P não é menor do 0,05;</li>
<li>o intervalo de confiança inclui o valor 3,5;</li>
<li>o valor <span class="math inline">\(t_0=-0.78741\)</span> está incluso na região de aceitação, como se pode comprovar a seguir.</li>
</ul>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df=</span><span class="dv">39</span>) <span class="co">#IC= 97.5%, alfa=5%/2=2.5%, n-1=39, positivo</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.022691</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span> (<span class="fl">0.025</span>, <span class="at">df=</span><span class="dv">39</span>)<span class="co">#IC= 95%(2.5%), alfa=5%/2=2.5%, n-1=39, negativo</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] -2.022691</code></pre>
</div>
</div>
<p>O teste padrão é bicaudal, nível de confiança de 95%, equivalente ao nível de significância de 5% (<code>conf.level = 0.95</code> <span class="math inline">\(=1- \alpha = 0.95\)</span>), mas essas especificações podem ser alteradas. Para testar se o valor da média amostra é menor do que um valor alegado, basta alterar o argumento <code>alternative = "less"</code> ou para <code>"greater"</code> para testar se a média amostral é maior como demonstrado na subseção 1.3 da seção de análise a seguir:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Testar H0 de que vida útil média = 3.5 anos contra H1&lt;3.5 anos</span></span>
<span id="cb73-2"><a href="#cb73-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(bateria<span class="sc">$</span>vida_util, <span class="at">mu=</span><span class="fl">3.5</span>, <span class="at">alternative=</span><span class="st">"less"</span>, <span class="at">conf.level=</span><span class="fl">0.95</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    One Sample t-test

data:  bateria$vida_util
t = -0.78741, df = 39, p-value = 0.2179
alternative hypothesis: true mean is less than 3.5
95 percent confidence interval:
    -Inf 3.59973
sample estimates:
mean of x 
   3.4125 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="fu">length</span>(bateria<span class="sc">$</span>vida_util) <span class="co"># No de obs.</span></span>
<span id="cb75-2"><a href="#cb75-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.95</span>,n<span class="dv">-1</span>) <span class="co"># t crítico unicaudal alfa=0.05</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1.684875</code></pre>
</div>
</div>
<p>A <strong>não rejeição de <span class="math inline">\(H_0\)</span></strong> pode ser novamente observada de três maneiras:</p>
<ul>
<li>O valor-P não é menor do 0,05;</li>
<li>O intervalo de confiança vai de -infinito até 3.59973, incluindo 3,5 no intervalo</li>
<li>O valor absoluto de <span class="math inline">\(t_0\)</span>, 0.7874, não excede o valor crítico unicaudal que é 1.684875.</li>
</ul>
</section>
</section>
<section id="análise-de-normalidade" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="análise-de-normalidade"><span class="header-section-number">5.4</span> Análise de normalidade</h2>
<p>Muitos testes estatísticos supõem que a distribuição da amostra siga uma distribuição particular, especialmente a normal. A verificação da qualidade de ajuste da distribuição da variável aleatória pode ser realizada por meior de exame gráfico e por testes formais.</p>
<section id="análise-gráfica-da-normalidade" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="análise-gráfica-da-normalidade"><span class="header-section-number">5.4.1</span> Análise gráfica da normalidade</h3>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(bateria<span class="sc">$</span>vida_util)</span>
<span id="cb77-2"><a href="#cb77-2" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(<span class="at">h=</span><span class="fu">mean</span>(bateria<span class="sc">$</span>vida_util),<span class="at">col=</span><span class="st">"blue"</span>,<span class="at">lty =</span> <span class="dv">2</span>) <span class="co"># linha horiz. na média</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-plot_baterias" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-plot_baterias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;34: Observações das vidas úteis de 40 baterias
</figcaption>
<div aria-describedby="fig-plot_baterias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-plot_baterias-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb78"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb78-1"><a href="#cb78-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">density</span>(bateria<span class="sc">$</span>vida_util))</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-dessidade" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-dessidade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;35: Densidade
</figcaption>
<div aria-describedby="fig-dessidade-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-dessidade-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) <span class="co"># Divide a janela graf.</span></span>
<span id="cb79-2"><a href="#cb79-2" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(bateria<span class="sc">$</span>vida_util,<span class="at">las=</span><span class="dv">1</span>)</span>
<span id="cb79-3"><a href="#cb79-3" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(bateria<span class="sc">$</span>vida_util) <span class="co"># Ajuste a normalidade</span></span>
<span id="cb79-4"><a href="#cb79-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-5"><a href="#cb79-5" aria-hidden="true" tabindex="-1"></a><span class="fu">qqnorm</span>(<span class="fu">scale</span>(bateria<span class="sc">$</span>vida_util))</span>
<span id="cb79-6"><a href="#cb79-6" aria-hidden="true" tabindex="-1"></a><span class="fu">qqline</span>(<span class="fu">scale</span>(bateria<span class="sc">$</span>vida_util))</span>
<span id="cb79-7"><a href="#cb79-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb79-8"><a href="#cb79-8" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfrow=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">2</span>)) <span class="co"># janela graf normal.</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-qqp_baterias" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-qqp_baterias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;36: QQplots - vida útteis de baterias
</figcaption>
<div aria-describedby="fig-qqp_baterias-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-qqp_baterias-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb80"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb80-1"><a href="#cb80-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma</span></span>
<span id="cb80-2"><a href="#cb80-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(bateria<span class="sc">$</span>vida_util,</span>
<span id="cb80-3"><a href="#cb80-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">freq=</span><span class="cn">FALSE</span>, </span>
<span id="cb80-4"><a href="#cb80-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">main =</span> <span class="st">"Histograma sobreposto pela curva normal"</span>)</span>
<span id="cb80-5"><a href="#cb80-5" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x, <span class="at">mean=</span><span class="fu">mean</span>(bateria<span class="sc">$</span>vida_util), <span class="at">sd=</span><span class="fu">sd</span>(bateria<span class="sc">$</span>vida_util)), <span class="at">col=</span><span class="st">"darkblue"</span>, <span class="at">lwd=</span><span class="dv">2</span>, <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">yaxt=</span><span class="st">"n"</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-hist_curva" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-hist_curva-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;37: Histograma sobreposto pela curva normal
</figcaption>
<div aria-describedby="fig-hist_curva-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-hist_curva-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histograma padronizado, densidade empírica vs curva normal.</span></span>
<span id="cb81-2"><a href="#cb81-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">scale</span>(bateria<span class="sc">$</span>vida_util), <span class="at">las=</span><span class="dv">1</span>, <span class="at">ylim=</span><span class="fu">c</span>(<span class="dv">0</span>,.<span class="dv">7</span>), <span class="at">freq=</span><span class="cn">FALSE</span>, <span class="at">main =</span> <span class="cn">NULL</span>)</span>
<span id="cb81-3"><a href="#cb81-3" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x), <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="st">'blue'</span>, <span class="at">lwd=</span><span class="dv">2</span>)</span>
<span id="cb81-4"><a href="#cb81-4" aria-hidden="true" tabindex="-1"></a><span class="co"># title("Histograma padronizado, densidade empírica vs curva normal")</span></span>
<span id="cb81-5"><a href="#cb81-5" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(<span class="fu">density</span>(<span class="fu">scale</span>(bateria<span class="sc">$</span>vida_util)), <span class="at">col=</span><span class="st">'red'</span>)</span>
<span id="cb81-6"><a href="#cb81-6" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(.<span class="dv">5</span>,<span class="fl">0.7</span>, <span class="fu">c</span>(<span class="st">"Dens. teórica"</span>,<span class="st">"Dens. empírica"</span>), <span class="at">fill=</span><span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>),<span class="at">box.col=</span><span class="dv">0</span>, <span class="at">border =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"red"</span>),<span class="at">horiz=</span>F)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-hist_curva_pad" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-hist_curva_pad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;38: Histograma padronizado, densidade empírica vs curva normal
</figcaption>
<div aria-describedby="fig-hist_curva_pad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-hist_curva_pad-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
</section>
<section id="testes-de-normalidade" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="testes-de-normalidade"><span class="header-section-number">5.4.2</span> Testes de normalidade</h3>
<p>Para testar se os dados seguem uma distribição normal, deve-se realizar um teste formal. Há vários disponíveis do R, contudo, o teste de Shapiro-Wilk tem sido indicado para pequenas amostras. O Shapiro-Wilk é um dos testes mais poderosos de normalidade, especialmente para pequenas amostras. Segundo Fávero et al.&nbsp;(2009), <strong>W</strong> é calculado por meio da seguinte equação:</p>
<p><span class="math display">\[W=\frac{\left(\sum\limits_{i=1}^{n}\alpha_ix_{(i)}\right)^2}{\sum\limits_{i=1}^{n}(x_1-x)^2}\]</span></p>
<p>onde <span class="math inline">\(x_{(i)}\)</span> são os valores da amostra ordenados; <span class="math inline">\(\alpha_i\)</span> são constantes obtidas a partir das médias, variâncias e covariâncias das estatísticas ordinais de uma amostra de dimensão <span class="math inline">\(n\)</span> de uma população normal; e <span class="math inline">\(x_1\)</span> é o menor valor.</p>
<p>Testa-se a hipótese nula de que os dados são normalmente distribuídos, logo, rejeita-se a normalidade se o valor-P for menor do que o nível de significância escolhido, no caso, menor do que 0,05.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb82"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb82-1"><a href="#cb82-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(bateria<span class="sc">$</span>vida_util) <span class="co"># Normalidade</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  bateria$vida_util
W = 0.97607, p-value = 0.5465</code></pre>
</div>
</div>
<p>não se pode rejeitar a normalidade dos dados porque o valor-P não é menor do que 0,05.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb84"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb84-1"><a href="#cb84-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(<span class="st">"nortest"</span>)</span>
<span id="cb84-2"><a href="#cb84-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lillie.test</span>(bateria<span class="sc">$</span>vida_util) <span class="co"># Lilliefors</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  bateria$vida_util
D = 0.10363, p-value = 0.344</code></pre>
</div>
</div>
</section>
<section id="exercício-2" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="exercício-2"><span class="header-section-number">5.4.3</span> Exercício</h3>
<p>Exemplo e dados obtidos em: http://www.instantr.com/2012/12/29/performing-a-one-sample-t-test-in-r/</p>
<p>As máquinas de uma fábrica devem envasar 500 ml de refrigerantes nas garrafas. Todavia, o fabricante suspeita que uma de suas máquinas está envasando um volume inferior de líquidos. Para investigar se a máquina está desrregulada, carregue o arquivo <strong>bottles.txt</strong> como o comando <code>read.table()</code>. Os dados são referentes a uma amostra aleatória de volumes de 20 garrafas de refrigerantes na máquina em suspeição e faça o que se pede:</p>
<ul>
<li>Examine graficamente a normalidade da distribuição;</li>
<li>Teste a normalidade da distribuição empírica com o teste de Shapiro-Wilk;</li>
<li>Realize o teste T com um nível de significância de 1%.</li>
</ul>
</section>
</section>
<section id="teste-de-hipótese-para-um-fator-com-dois-níveis-duas-amostras-independentes." class="level2" data-number="5.5">
<h2 data-number="5.5" class="anchored" data-anchor-id="teste-de-hipótese-para-um-fator-com-dois-níveis-duas-amostras-independentes."><span class="header-section-number">5.5</span> Teste de hipótese para um fator com dois níveis (duas amostras independentes).</h2>
<p><span class="math display">\[
\begin{array}{llcc}
H_0&amp;: \mu_1=\mu_2&amp; &amp;  \\
H_{1\textrm{(possíveis)}}&amp;:\mu_1\neq\mu_2, &amp; \mu_1&gt;\mu_2 \; \text{ou} &amp; \mu_1&lt;\mu_2
\end{array}
\]</span></p>
<p>Consideremos o experimento de resistência a tensão adesiva (<em>Tension Bond Strength data</em>) de duas formulações de argamassa de cimento Portland, o modificado (<em>Modified</em>) e o não modificado (<em>Unmodified</em>). Nesse caso, o que temos é <strong>um fator</strong> que é a formulação da argamassa, com <strong>dois níveis</strong> (Modified e Unmodified) e <strong>uma variável resposta</strong>, a resistência a tração.</p>
<p>O que pretende é verificar se a resistência à tensão adesiva das diferentes formulações de argamassa são ou não iguais. Em termos de hipóteses, temos as seguintes:</p>
<p><span class="math display">\[H_0: \mu_M=\mu_U\]</span> <span class="math display">\[H_1: \mu_M\neq\mu_U\]</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb86"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb86-1"><a href="#cb86-1" aria-hidden="true" tabindex="-1"></a><span class="co"># resistência a tensão adesiva (Tension Bond Strength data) (Tab. 2-1, p. 24)</span></span>
<span id="cb86-2"><a href="#cb86-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-3"><a href="#cb86-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-4"><a href="#cb86-4" aria-hidden="true" tabindex="-1"></a>y1 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">16.85</span>,<span class="fl">16.40</span>,<span class="fl">17.21</span>,<span class="fl">16.35</span>,<span class="fl">16.52</span>,<span class="fl">17.04</span>,<span class="fl">16.96</span>,<span class="fl">17.15</span>,<span class="fl">16.59</span>,<span class="fl">16.57</span>)</span>
<span id="cb86-5"><a href="#cb86-5" aria-hidden="true" tabindex="-1"></a>y2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fl">16.62</span>,<span class="fl">16.75</span>,<span class="fl">17.37</span>,<span class="fl">17.12</span>,<span class="fl">16.98</span>,<span class="fl">16.87</span>,<span class="fl">17.34</span>,<span class="fl">17.02</span>,<span class="fl">17.08</span>,<span class="fl">17.27</span>)</span>
<span id="cb86-6"><a href="#cb86-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-7"><a href="#cb86-7" aria-hidden="true" tabindex="-1"></a><span class="co"># y1 = modificado</span></span>
<span id="cb86-8"><a href="#cb86-8" aria-hidden="true" tabindex="-1"></a><span class="co"># y2 = naomod</span></span>
<span id="cb86-9"><a href="#cb86-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb86-10"><a href="#cb86-10" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(y1)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 16.764</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb88"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb88-1"><a href="#cb88-1" aria-hidden="true" tabindex="-1"></a><span class="fu">mean</span>(y2)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 17.042</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb90"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb90-1"><a href="#cb90-1" aria-hidden="true" tabindex="-1"></a>resp <span class="ot">&lt;-</span> <span class="fu">c</span>(y1,y2) <span class="co"># num só vetor</span></span>
<span id="cb90-2"><a href="#cb90-2" aria-hidden="true" tabindex="-1"></a>resp</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] 16.85 16.40 17.21 16.35 16.52 17.04 16.96 17.15 16.59 16.57 16.62 16.75
[13] 17.37 17.12 16.98 16.87 17.34 17.02 17.08 17.27</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb92"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb92-1"><a href="#cb92-1" aria-hidden="true" tabindex="-1"></a>argamassa <span class="ot">&lt;-</span> <span class="fu">rep</span>(<span class="fu">c</span>(<span class="st">"Modificado"</span>, <span class="st">"NaoMod"</span>), <span class="fu">c</span>(<span class="dv">10</span>,<span class="dv">10</span>))</span>
<span id="cb92-2"><a href="#cb92-2" aria-hidden="true" tabindex="-1"></a>argamassa</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "Modificado" "Modificado" "Modificado" "Modificado" "Modificado"
 [6] "Modificado" "Modificado" "Modificado" "Modificado" "Modificado"
[11] "NaoMod"     "NaoMod"     "NaoMod"     "NaoMod"     "NaoMod"    
[16] "NaoMod"     "NaoMod"     "NaoMod"     "NaoMod"     "NaoMod"    </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb94"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb94-1"><a href="#cb94-1" aria-hidden="true" tabindex="-1"></a>dados <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(argamassa, resp)</span>
<span id="cb94-2"><a href="#cb94-2" aria-hidden="true" tabindex="-1"></a>dados<span class="sc">$</span>argamassa <span class="ot">&lt;-</span> <span class="fu">factor</span>(dados<span class="sc">$</span>argamassa) <span class="co"># Converter em fator</span></span>
<span id="cb94-3"><a href="#cb94-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb94-4"><a href="#cb94-4" aria-hidden="true" tabindex="-1"></a>y.means <span class="ot">&lt;-</span> <span class="fu">tapply</span>(dados<span class="sc">$</span>resp, dados<span class="sc">$</span>argamassa, mean)</span>
<span id="cb94-5"><a href="#cb94-5" aria-hidden="true" tabindex="-1"></a>y.means</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Modificado     NaoMod 
    16.764     17.042 </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb96"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb96-1"><a href="#cb96-1" aria-hidden="true" tabindex="-1"></a><span class="fu">stripchart</span>(resp <span class="sc">~</span> argamassa,</span>
<span id="cb96-2"><a href="#cb96-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">data =</span> dados,</span>
<span id="cb96-3"><a href="#cb96-3" aria-hidden="true" tabindex="-1"></a>           <span class="at">vertical =</span> <span class="cn">TRUE</span>,</span>
<span id="cb96-4"><a href="#cb96-4" aria-hidden="true" tabindex="-1"></a>           <span class="at">method =</span> <span class="st">"jitter"</span>,</span>
<span id="cb96-5"><a href="#cb96-5" aria-hidden="true" tabindex="-1"></a>           <span class="at">pch =</span> <span class="dv">19</span>,</span>
<span id="cb96-6"><a href="#cb96-6" aria-hidden="true" tabindex="-1"></a>           <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"blue"</span>, <span class="st">"darkgreen"</span>),</span>
<span id="cb96-7"><a href="#cb96-7" aria-hidden="true" tabindex="-1"></a>           <span class="at">xlab =</span> <span class="fu">expression</span>(<span class="fu">paste</span>(<span class="st">"Strength ("</span>, kgf<span class="sc">/</span>cm<span class="sc">^</span><span class="dv">2</span>, <span class="st">")"</span>)))</span>
<span id="cb96-8"><a href="#cb96-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-9"><a href="#cb96-9" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, y.means, <span class="at">pch =</span> <span class="dv">23</span>, <span class="at">bg =</span> <span class="st">"yellow"</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span>
<span id="cb96-10"><a href="#cb96-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb96-11"><a href="#cb96-11" aria-hidden="true" tabindex="-1"></a><span class="fu">text</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, y.means,</span>
<span id="cb96-12"><a href="#cb96-12" aria-hidden="true" tabindex="-1"></a>     <span class="at">labels =</span> <span class="fu">round</span>(y.means, <span class="dv">2</span>),</span>
<span id="cb96-13"><a href="#cb96-13" aria-hidden="true" tabindex="-1"></a>     <span class="at">pos =</span> <span class="dv">3</span>, <span class="at">cex =</span> .<span class="dv">8</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O gráfico de pontos (<em>strichart</em>) sugere que a distribuição amostral de resistência das fibras não modificadas (<em>Unmodified</em>) apresentam valores superiores à distribuição da modificada. As médias, indicadas cadas pelas setas, exibem que a resistência das modificadas é ligeiramente maior do que resistência média das não modificadas.</p>
<p>A seguir, elabora-se o Boxplot com médias indicadas por ‘+’</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(resp <span class="sc">~</span> argamassa,</span>
<span id="cb97-2"><a href="#cb97-2" aria-hidden="true" tabindex="-1"></a>        <span class="at">data =</span> dados,</span>
<span id="cb97-3"><a href="#cb97-3" aria-hidden="true" tabindex="-1"></a>        <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"slategray3"</span>,<span class="st">"indianred1"</span>),</span>
<span id="cb97-4"><a href="#cb97-4" aria-hidden="true" tabindex="-1"></a>        <span class="at">las =</span> <span class="dv">1</span>,</span>
<span id="cb97-5"><a href="#cb97-5" aria-hidden="true" tabindex="-1"></a>        <span class="at">ylab =</span> <span class="st">"Strength (kgf/cm^2)"</span>)</span>
<span id="cb97-6"><a href="#cb97-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-7"><a href="#cb97-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb97-8"><a href="#cb97-8" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>, y.means, <span class="at">pch =</span> <span class="dv">23</span>, <span class="at">bg =</span> <span class="st">"yellow"</span>, <span class="at">cex =</span> <span class="fl">1.5</span>)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="index_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Verificação gráfica da normalidade dos dados</p>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-qqp_argamassa" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-qqp_argamassa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;39: QQplot Argamassa
</figcaption>
<div aria-describedby="fig-qqp_argamassa-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-qqp_argamassa-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div id="fig-qqp_argamassa_pad" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-qqp_argamassa_pad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;40: QQplot Argamassa - dados padronizados
</figcaption>
<div aria-describedby="fig-qqp_argamassa_pad-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-qqp_argamassa_pad-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb98"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb98-1"><a href="#cb98-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogramas</span></span>
<span id="cb98-2"><a href="#cb98-2" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">scale</span>(dados<span class="sc">$</span>resp[dados<span class="sc">$</span>argamassa <span class="sc">==</span> <span class="st">"Modificado"</span>]), <span class="at">freq=</span><span class="cn">FALSE</span>, <span class="at">xlab =</span> <span class="st">"Resistência"</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb98-3"><a href="#cb98-3" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x), <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="dv">2</span>); <span class="fu">lines</span>(<span class="fu">density</span>(<span class="fu">scale</span>(dados<span class="sc">$</span>resp[dados<span class="sc">$</span>argamassa <span class="sc">==</span> <span class="st">"Modificado"</span>])), <span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb98-4"><a href="#cb98-4" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(.<span class="dv">5</span>,<span class="fl">0.6</span>, <span class="fu">c</span>(<span class="st">"Dens. teórica"</span>,<span class="st">"Dens. empírica"</span>), <span class="at">fill=</span><span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>),<span class="at">box.col=</span><span class="dv">0</span>, <span class="at">horiz=</span>F )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-hist_mod" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-hist_mod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;41: Histograma de Argamassa Modificada
</figcaption>
<div aria-describedby="fig-hist_mod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-hist_mod-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<div class="cell" data-layout-align="center">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(<span class="fu">scale</span>(dados<span class="sc">$</span>resp[dados<span class="sc">$</span>argamassa <span class="sc">==</span> <span class="st">"NaoMod"</span>]), <span class="at">freq=</span><span class="cn">FALSE</span>, <span class="at">xlab =</span> <span class="st">"Resistência"</span>, <span class="at">main =</span> <span class="st">""</span>)</span>
<span id="cb99-2"><a href="#cb99-2" aria-hidden="true" tabindex="-1"></a><span class="fu">curve</span>(<span class="fu">dnorm</span>(x), <span class="at">add=</span><span class="cn">TRUE</span>, <span class="at">col=</span><span class="dv">2</span>); <span class="fu">lines</span>(<span class="fu">density</span>(<span class="fu">scale</span>(dados<span class="sc">$</span>resp[dados<span class="sc">$</span>argamassa <span class="sc">==</span> <span class="st">"NaoMod"</span>])), <span class="at">col=</span><span class="dv">3</span>)</span>
<span id="cb99-3"><a href="#cb99-3" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="sc">-</span><span class="dv">2</span>,<span class="fl">0.4</span>, <span class="fu">c</span>(<span class="st">"Dens. teórica"</span>,<span class="st">"Dens. empírica"</span>), <span class="at">col=</span><span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>),<span class="at">lty=</span><span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">1</span>),<span class="at">box.col=</span><span class="dv">0</span>, <span class="at">horiz=</span>F )</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div id="fig-hist_nmod" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-fig" id="fig-hist_nmod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;42: Histograma de Argamassa Não Modificada
</figcaption>
<div aria-describedby="fig-hist_nmod-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-hist_nmod-1.png" class="img-fluid quarto-figure quarto-figure-center figure-img" width="672">
</div>
</figure>
</div>
</div>
</div>
<section id="teste-de-normalidade-dos-dados" class="level3" data-number="5.5.1">
<h3 data-number="5.5.1" class="anchored" data-anchor-id="teste-de-normalidade-dos-dados"><span class="header-section-number">5.5.1</span> Teste de normalidade dos dados</h3>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb100"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb100-1"><a href="#cb100-1" aria-hidden="true" tabindex="-1"></a><span class="co"># 2.3 TESTE DE DUAS médias INDEPENDENTES</span></span>
<span id="cb100-2"><a href="#cb100-2" aria-hidden="true" tabindex="-1"></a><span class="do">### Teste de normalidade</span></span>
<span id="cb100-3"><a href="#cb100-3" aria-hidden="true" tabindex="-1"></a><span class="fu">tapply</span>(dados<span class="sc">$</span>resp, dados<span class="sc">$</span>argamassa, shapiro.test)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>$Modificado

    Shapiro-Wilk normality test

data:  X[[i]]
W = 0.91863, p-value = 0.3457


$NaoMod

    Shapiro-Wilk normality test

data:  X[[i]]
W = 0.96262, p-value = 0.8153</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb102"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb102-1"><a href="#cb102-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Normalidade = OK, OK</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="teste-de-homogeneidade-das-variâncias-homocedasticidade" class="level3" data-number="5.5.2">
<h3 data-number="5.5.2" class="anchored" data-anchor-id="teste-de-homogeneidade-das-variâncias-homocedasticidade"><span class="header-section-number">5.5.2</span> Teste de homogeneidade das variâncias (Homocedasticidade)</h3>
<p>Os dois testes de homocedasticidade são o teste F e o teste de Levene (1960). Nos dois casos, testam-se as seguintes hipóteses:</p>
<p><span class="math display">\[H_0: \sigma_1=\sigma_2\]</span> <span class="math display">\[H_1: \sigma_1\ne\sigma_2\]</span></p>
<section id="teste-f-de-homogeneidade-de-variâncias" class="level4" data-number="5.5.2.1">
<h4 data-number="5.5.2.1" class="anchored" data-anchor-id="teste-f-de-homogeneidade-de-variâncias"><span class="header-section-number">5.5.2.1</span> Teste F de homogeneidade de variâncias</h4>
<p>O teste F para homogeneidade de variâncias é o quociente entre as variâncias das amostras, <span class="math inline">\(s_1^2\)</span> and <span class="math inline">\(s_2^2\)</span>.</p>
<p><span class="math display">\[F=\frac{s_1^2}{s_2^2}\]</span></p>
<p>Com <span class="math inline">\(n_1-1\)</span> graus de liberdade para o numerador e <span class="math inline">\(n_2-1\)</span> graus de liberdade para o denominador.</p>
<p>No R, a função <span class="math inline">\(var.test()\)</span> realiza o teste F para duas variâncias, podendo ser:</p>
<ul>
<li><code>var.test(respostas ~ tratamento, data)</code> no caso das respostas estarem num vetor e os tratamentos noutro ou</li>
<li><code>var.test(respostas 1, respostas 2, data)</code> no caso das respostas dos tratamentos estarem em vetores separados.</li>
</ul>
<p>A seguir, os comandos do teste F para as variâncias das distribuições amostrais dos ensaios de resistência a tensão adesiva de duas formulações de argamassa do exemplo.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Teste F de homogeneidade de variâncias</span></span>
<span id="cb103-2"><a href="#cb103-2" aria-hidden="true" tabindex="-1"></a><span class="fu">var.test</span>(resp <span class="sc">~</span> argamassa, <span class="at">data =</span> dados)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    F test to compare two variances

data:  resp by argamassa
F = 1.6293, num df = 9, denom df = 9, p-value = 0.4785
alternative hypothesis: true ratio of variances is not equal to 1
95 percent confidence interval:
 0.4046845 6.5593806
sample estimates:
ratio of variances 
          1.629257 </code></pre>
</div>
</div>
<p>Como se pode observar nos resultados, o valor P da estatística F é maior do que significância estabelecida, <span class="math inline">\(F(9, 9) = 1.6293, p = .4785\)</span>, de modo que não se pode rejeitar a hipótese nula de que homocedasticidade, ou seja, as variâncias das amostras são iguais.</p>
</section>
<section id="o-teste-de-levene" class="level4" data-number="5.5.2.2">
<h4 data-number="5.5.2.2" class="anchored" data-anchor-id="o-teste-de-levene"><span class="header-section-number">5.5.2.2</span> O Teste de Levene</h4>
<p>O teste de Levene (1960) testa a hipótese nula de que as variâncias das amostras são iguais. Fávero et al.&nbsp;(2009) explicam que estatística <span class="math inline">\(L\)</span> é dada por</p>
<p><span class="math display">\[L=\frac{N-k}{k-1}\times
\frac{\sum\limits_{i=1}^{k} n_i \left(\bar{Z}_i-\bar{Z}\right)^2}{\sum\limits_{i=1}^{k}\sum\limits_{j=1}^{n_i}\left(\bar{Z}_{ij}-\bar{Z}_i\right)^2}\]</span></p>
<p>em que <span class="math inline">\(n_i\)</span> é a dimensão de cada uma das <span class="math inline">\(k\)</span> amostras ou tratamentos e <span class="math inline">\(N\)</span>, a dimensão da amostra total. A variável <span class="math inline">\(Z\)</span> é definida como</p>
<p><span class="math display">\[Z_{ij} = |X_{ij} - \bar{X}_i| \quad (i = 1, ..., k\ e\ j = 1, ..., n_i)\]</span></p>
<p>em que <span class="math inline">\(X_{ij}\)</span> é a observação <span class="math inline">\(j\)</span> da amostra <span class="math inline">\(i\)</span> e <span class="math inline">\(\bar{X}_i\)</span> é a média da amostra <span class="math inline">\(i\)</span>.</p>
<p>No R, o teste de Levene pode ser realizado pela função <code>leveneTest()</code> do pacote <code>car</code>, que por <em>default</em> o teste de Brown-Forsythe baseado na mediana, o que o torna um mais robusto.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Teste de Levene</span></span>
<span id="cb105-2"><a href="#cb105-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-3"><a href="#cb105-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb105-4"><a href="#cb105-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb105-5"><a href="#cb105-5" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(resp <span class="sc">~</span> argamassa ,<span class="at">data=</span>dados) <span class="co"># Brown-Forsythe test</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = median)
      Df F value Pr(&gt;F)
group  1  1.9528 0.1793
      18               </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">leveneTest</span>(resp <span class="sc">~</span> argamassa, <span class="at">center =</span> mean ,<span class="at">data=</span>dados) <span class="co"># Levene</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Levene's Test for Homogeneity of Variance (center = mean)
      Df F value Pr(&gt;F)
group  1  2.0807 0.1663
      18               </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Homocedasticidade = OK: variâncias iguais</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
</section>
<section id="o-teste-t-para-dois-tratamentos-independentes" class="level3" data-number="5.5.3">
<h3 data-number="5.5.3" class="anchored" data-anchor-id="o-teste-t-para-dois-tratamentos-independentes"><span class="header-section-number">5.5.3</span> O teste t para dois tratamentos independentes</h3>
<p>Finalmente, tendo em conta que as distribuições são normalmente distribuídas, pode-se realizar o teste t de duas maneiras conforme as variâncias das amostram sejam ou não iguais.</p>
<p>No caso das variâncias serem iguais, <span class="math inline">\(s_1^2\)</span> e <span class="math inline">\(s_2^2\)</span>, significa que ambas estimam o mesmo valor, podendo ser combinadas numa estimativa única <span class="math inline">\(s_p^2\)</span>.</p>
<p><span class="math display">\[S_p^2=\frac{(n_1-1)s_1^2+(n_2-1)s_2^2}{n_1+n_2-2}\]</span></p>
<p>Nesse caso, para testar <span class="math inline">\(H_0\)</span>, a estatística teste é a seguinte:</p>
<p><span class="math display">\[t_0=\frac{\bar{x_1}-\bar{x_2}}{s_p^2\sqrt{\frac{1}{n_1}+\frac{1}{n_2}}}\]</span></p>
<p>Se <span class="math inline">\(H_0\)</span> for verdadeira, <span class="math inline">\(t_0\)</span> é distribuída como <span class="math inline">\(t_{n1+n2-2}\)</span>, para o teste bicaudal, sendo, contudo rejeitada em favor de <span class="math inline">\(H_1\)</span> se <span class="math inline">\(|t_0| \geq t_{\alpha/2, n1+n2-2}\)</span>.</p>
<p>Todavia se não for possível supor que as variâncias desconhecidas são iguais, que não existe um teste t exato para <span class="math inline">\(H_0:\mu_1=\mu_2\)</span>,como explicam Hines et al.&nbsp;Nesse caso, pode ser utilizado a estatística</p>
<p><span class="math display">\[t_0^*=\frac{\bar{x_1}-\bar{x_2}}{\sqrt{\frac{s_1^2}{n_1}+\frac{s_2^2}{n_2}}}\]</span></p>
<p>que, se a hipótese nula for verdadeira, segue aproximadamente distribuição t, com graus de liberdade calculados por</p>
<p><span class="math display">\[\nu=\frac{\left(\tfrac{s_1^2}{n_1}+\tfrac{s_2^2}{n_2}\right)^2}{\frac{\left(\tfrac{s_1^2}{n_1}\right)^2}{n_1+1}+\frac{\left(\tfrac{s_2^2}{n_2}\right)^2}{n_2+1}}-2\]</span></p>
<p>No R, como será demonstrado a frente, os dois casos são facilmente tratados. Se as variâncias forem iguais, basta ajustar o argumento <code>var.equal=T</code>, mas se forem diferentes, ajusta-se o argumento <code>var.equal=F</code> ou se deixa em branco, uma vez que este é o <em>default</em> da função.</p>
<p>No exemplo, as etapas do teste t seriam realizadas da seguinte maneira:</p>
<ol type="1">
<li>O teste de Shapiro-Wilk indica que a suposição de normalidade não é violada por nenhuma das amostras, o teste F e o teste de Levene indicam que as variâncias podem ser consideradas homogêneas.</li>
<li>Testa-se se as resistências são iguais, <span class="math inline">\(H_0:\mu_1=\mu_2\)</span> , contra <span class="math inline">\(H_1:\mu_1\ne\mu_2\)</span>.</li>
<li>O nível de significância do teste foi fixado em <span class="math inline">\(\alpha = 5\%\)</span> ou 0,05;</li>
<li>O valor <span class="math inline">\(t_{0,025, 18} = 2,0227\)</span>, um vez que <span class="math inline">\(n_1=n_2 =10\)</span>, <span class="math inline">\(\dfrac{0,05}{2} = 0,025\)</span> e <span class="math inline">\(\nu = 10+10-2=18\)</span>.</li>
<li>Calcular <span class="math inline">\(t_0\)</span>.</li>
<li>Uma vez que <span class="math inline">\(|t_0|= 2.1869 &gt; t_{0,025, 18}= 2,1009\)</span>, rejeita-se <span class="math inline">\(H_0\)</span>. O valor- P é <span class="math inline">\(0,0422 &lt;  \alpha = 0,05\)</span>, o que permite rejeitar <span class="math inline">\(H_0\)</span>. A conclusão é de que se pode afirmar que as resistências à tração fibras são diferentes.</li>
</ol>
<p>A seguir os comandos do teste t para dois tratamentos independentes no R, considerando variâncias iguais.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb110"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb110-1"><a href="#cb110-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Teste t para amostras independentes com variáveis iguais</span></span>
<span id="cb110-2"><a href="#cb110-2" aria-hidden="true" tabindex="-1"></a><span class="fu">t.test</span>(resp <span class="sc">~</span> argamassa, <span class="at">var.equal=</span>T)</span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Two Sample t-test

data:  resp by argamassa
t = -2.1869, df = 18, p-value = 0.0422
alternative hypothesis: true difference in means between group Modificado and group NaoMod is not equal to 0
95 percent confidence interval:
 -0.54507339 -0.01092661
sample estimates:
mean in group Modificado     mean in group NaoMod 
                  16.764                   17.042 </code></pre>
</div>
</div>
<p>Para se obter o valor crítico <span class="math inline">\(t_{0,05/2;18}\)</span></p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb112"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb112-1"><a href="#cb112-1" aria-hidden="true" tabindex="-1"></a><span class="fu">qt</span>(<span class="fl">0.975</span>, <span class="at">df=</span><span class="dv">18</span>) <span class="co">#IC= 97.5%, alfa=5%/2=2.5%, 10+10-2=18, positivo</span></span></code></pre></div><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 2.100922</code></pre>
</div>
</div>
<p><span class="math inline">\(|t_0|=2.1869&gt;2.100922\)</span></p>
<p>O valor em módulo de <span class="math inline">\(t_0\)</span> é maior do que o valor crítico tabelado, indicando não se pode aceitar <span class="math inline">\(H_0\)</span>.</p>
<p>Portanto, a <strong>rejeição</strong> de <span class="math inline">\(H_0\)</span> pode ser observada de três maneiras:</p>
<ul>
<li>O valor-P é menor do 0,05 (nível de significância);</li>
<li>O intervalo de confiança vai de -0.54507339 a -0.01092661, excluindo diferença zero do intervalo</li>
<li>O valor absoluto do valor t calculado da diferença entre as médias, <span class="math inline">\(|t_0|=2,1869\)</span>, excede o valor crítico bicaudal que é 2,100922.</li>
</ul>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copiada");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copiada");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>